examples/pom.xml, util/pom.xml, util/src/main/java/io/kubernetes/client/util/Config.java, util/src/main/java/io/kubernetes/client/util/KubeConfig.java, util/src/test/java/io/kuberentes/client/util/ConfigTest.java
Fixes #12 
Builds on top of #7, that PR should be merged first.
=> Automagic client creation

examples/src/main/java/io/kubernetes/client/examples/Example.java, examples/src/main/java/io/kubernetes/client/examples/WebSocketsExample.java, kubernetes/.swagger-codegen-ignore, kubernetes/src/main/java/io/kubernetes/client/ApiClient.java, util/pom.xml, util/src/main/java/io/kubernetes/client/util/Config.java, util/src/main/java/io/kubernetes/client/util/KubeConfig.java, util/src/main/java/io/kubernetes/client/util/WebSockets.java, util/src/test/java/io/kuberentes/client/util/ConfigTest.java
Ready for review
Fixes #18 
Depends on #17
=> Web socket support.

util/src/main/java/io/kubernetes/client/util/Config.java, util/src/main/java/io/kubernetes/client/util/KubeConfig.java
@mbohlool this is needed for Bronze certification
Fixes https://github.com/kubernetes-client/java/issues/33
=> Support insecure ca root validation.

examples/pom.xml, examples/src/main/java/io/kubernetes/client/examples/ExecExample.java, examples/src/main/java/io/kubernetes/client/examples/WebSocketsExample.java, util/pom.xml, util/src/main/java/io/kubernetes/client/Exec.java, util/src/main/java/io/kubernetes/client/util/WebSockets.java
=> Initial implementation of Exec.

README.md
Look like our support level is Silver (we support watch). I've fixed that in this PR and added relevant installation instruction from auto generated README file. We need to update this procedures once we released the client.
=> Promote client capabilities to Silver and add relevant installation steps

kubernetes/pom.xml
The generated javadoc comments in the `models` packages contain several
`<` characters which the java8 doclint plugin rejects. Note - this means if you
build with java8 you will _not_ have javadocs. Another solution would be
to fix the stems for the comments in that package, but I'm not sure how
to go about that.
=> Disable doclint when building with java8

examples/pom.xml, kubernetes/pom.xml, pom.xml, util/pom.xml
I realized we need to build & release the `util` submodule as well. I moved the release-specific bits of the `kubernetes/pom.xml` to the top-level `pom.xml`, and added a flag to the `examples` module to avoid releasing that.
=> Release parent project (to release util module)

examples/src/main/java/io/kubernetes/client/examples/AttachExample.java, examples/src/main/java/io/kubernetes/client/examples/Example.java, examples/src/main/java/io/kubernetes/client/examples/WebSocketsExample.java, util/pom.xml, util/src/main/java/io/kubernetes/client/Attach.java, util/src/main/java/io/kubernetes/client/Exec.java, util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java, util/src/main/java/io/kubernetes/client/util/WebSockets.java
(also re-factor the Exec library)
Fixes #10
=> Implement Attach

README.md, examples/pom.xml, kubernetes/pom.xml, pom.xml, util/pom.xml, util/src/main/java/io/kubernetes/client/Attach.java, util/src/main/java/io/kubernetes/client/Exec.java, util/src/main/java/io/kubernetes/client/util/Config.java, util/src/main/java/io/kubernetes/client/util/Watch.java, util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java, util/src/main/java/io/kubernetes/client/util/authenticators/Authenticator.java
Sorry for the churn, there were a few things left to fix
Non [maven-release-plugin] commits were written by me to get the release to pass.
Sonatypes validation of our artifacts has passed, I just need to update the JIRA ticket to indicate we've done our first release and the artifacts should be available after that.
=> Release 0.1

util/src/main/java/io/kubernetes/client/util/Config.java
Given that the `KubeConfig` object is public, exposing a constructor like this is useful to users who want to have more control in how the client authenticates. For example, being able to load a `KubeConfig` from disk, edit the context, and then authenticate with the user & cluster in that context is useful.
=> Allow ApiClient to be constructed from KubeConfig

examples/pom.xml, examples/src/main/java/io/kubernetes/client/examples/ProtoExample.java, pom.xml, proto/pom.xml, util/pom.xml, util/src/main/java/io/kubernetes/client/ProtoClient.java
This is pretty simple, but it gives a flavor before I do more development.
Comments/feedback very welcome.
@lwander @mbohlool
=> initial protobuf client.

util/src/main/java/io/kubernetes/client/util/KubeConfig.java
Before this change, any attempt to load a kubeconfig w/o current-context field would NPE. Since `kubectl` doesn't have this behavior, and we expose the ability to set a custom context on a kubeconfig, we shouldn't crash here.
=> Allow kubeconfig to be loaded without current-context

CHANGELOG.md, README.md, examples/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, util/pom.xml
https://github.com/kubernetes-client/java/issues/82
=> Prep for 1.0.0-beta1 release

examples/src/main/java/io/kubernetes/client/examples/PortForwardExample.java, util/src/main/java/io/kubernetes/client/PortForward.java, util/src/main/java/io/kubernetes/client/util/WebSockets.java
Fixes #11 
Uses WebSocket for Port Forward as added by https://github.com/kubernetes/kubernetes/pull/33684
@mbohlool @lwander
=> Add support for PortForward.

examples/src/main/java/io/kubernetes/client/examples/LogsExample.java, util/src/main/java/io/kubernetes/client/Logs.java, util/src/main/java/io/kubernetes/client/PodLogs.java
Adds capability to get logs as a stream, not just as a string.
=> Add an initial logs utility class.

util/src/main/java/io/kubernetes/client/util/Config.java
`ApiClient#setUsername`, `ApiClient#setPassword`, and `ApiClient#setAccessToken` all correspond to different underlying authentication mechanisms for Swagger. In order for these to be applied the mechanism must be enabled in two places: it must be registered in the client and it must be specified for the API request in Swagger JSON. 
Currently, this client only has `BearerToken` and `HttpBasicAuth` registered. As such all calls to `ApiClient#setAccessToken` will fail complaining that `OAuth` is not registered. 
Further, although `HttpBasicAuth` is registered, it is not specified for any API requests in the Swagger JSON. As such `setUsername`/`setPassword` calls will work but will never be passed when making API requests.
To get around this, this PR uses `setApiKey` for all authentication …
=> Use setApiKey over setUsername/Password/AccessToken as they are not used

kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java
Add an `IntOrString` model along with its type adapter. This type allows us to receive a type from the API and then re-serialize it without changing its type. Previously all values received from the API were converted to strings. This meant that if returned to the API, the API would respond with a 400 Bad Request because the type was not always as expected (e.g. `maxUnavailable` should either be an `int` or a `String` that ends with a `%` - if previously `1` had been specified it would be rejected as it was not `1%`).
There will be a corresponding PR in [the gen repo](https://github.com/kubernetes-client/gen) for this.
=> Add IntOrString model and GSON adapter

examples/src/main/java/io/kubernetes/client/examples/AttachExample.java, examples/src/main/java/io/kubernetes/client/examples/ExecExample.java, util/src/main/java/io/kubernetes/client/Attach.java, util/src/main/java/io/kubernetes/client/ProtoClient.java, util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
Apropos of https://github.com/kubernetes-client/java/pull/95
I audited the rest of our code...
=> Fix up some potential leaks, by calling close()

examples/pom.xml, proto/pom.xml
`maven-deploy-plugin@2.5.3` doesn't exist in [Maven Central](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.apache.maven.plugins%22%20AND%20a%3A%22maven-deploy-plugin%22) and prevents deploying it to our local Nexus. 
It's a valid version of `maven-release-plugin` so I think this may have been a copy-paste error.
=> Use a version of deploy-plugin that exists in Maven Central

util/src/main/java/io/kubernetes/client/PortForward.java
The `PortForwarder` class doesn't work for higher port numbers. Java converts bytes by default to signed integers. Therefore this formula:
```
int port = data[0] + data[1] * 256;
```
can fail because data[0] and data[1] might be interpreted as negative numbers. For example when trying to forward port `8080`, `port` will be set to `7824` (-112 + 31*256). This will cause the PortForwarder not to work (it will not find the streams for port `8080`). 
This PR makes sure that the bytes are interpreted as unsigned integers and and makes sure that the port number will be as expected.
=> PortForwarder doesn't work for higher port numbers

util/src/main/java/io/kubernetes/client/util/Watch.java
Fixes https://github.com/kubernetes-client/java/issues/164
@bhabermas
@jberhard
@mbohlool
=> When watch can't parse an object, try to parse it to a Status.

util/pom.xml
com.github.stefanbirkner:system-rules is licensed under Common Public License 1.0, which is "weak copyleft" licence according to the[ ASF policies](https://www.apache.org/legal/resolved.html).
As it is used only in test files I propose to change the scope of the dependency to test. With test scope it won't be included in the final artifacts and will be easier to use this client project from Apache projects.
=> Use junit system-rules dependency with test scope

examples/src/main/java/io/kubernetes/client/examples/PatchExample.java
as this library doesn't support strategic merge patch(<i>application/strategic-merge-patch+json</i>) yet (issue https://github.com/kubernetes-client/java/issues/127), following example demonstrates patching of deployment using Json Patch (<i>application/json-patch+json</i>). this can also be extended to patching of other k8 objects<br> 
For generating Json Patches, <a href="http://jsonpatch.com/">http://jsonpatch.com</a>.
<p> PatchExample does following:</p>
<ul>
<li>Creates deployment hello-node with <b>terminationGracePeriodSeconds</b> value as 30.
<li>Patches deployment hello-node with <b>terminationGracePeriodSeconds</b> value as 27.
</ul>
=> working example of patch deployment

util/src/main/java/io/kubernetes/client/util/credentials/KubeconfigAuthentication.java
when loading certs through Kubeconfig (Config.fromConfig(..)  || Config.defaultClient(..) || ClientBuilder.defaultClient())  getting following error :
```
Exception in thread "main" io.kubernetes.client.ApiException: Unauthorized
at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:883)
at io.kubernetes.client.ApiClient.execute(ApiClient.java:799)
at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:18462)
at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:18440)
at io.kubernetes.client.examples.Example.main(Example.java:40)
```
it is because keyManagers are not set, when loading certs in **KubeconfigAuthentication.provide**
=> fix for Unauthorized error when loading certs through kubeconfig

util/pom.xml, util/src/main/java/io/kubernetes/client/util/Yaml.java, util/src/test/java/io/kubernetes/client/util/YamlTest.java
Closes #170 
@kondapally1989 @zysimplelife @lwander 
Code now looks like:
```java
V1Pod pod = (V1Pod) Yaml.load(new File("my-file.yaml"));
```
=> Add support for easier YAML loading.

examples/src/main/java/io/kubernetes/client/examples/ExecExample.java, util/src/main/java/io/kubernetes/client/Exec.java, util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java, util/src/main/java/io/kubernetes/client/util/WebSockets.java, util/src/test/java/io/kubernetes/client/ExecTest.java
Three improvements:
1) Correct exitValue() to match Process.exitValue() documentation and implement waitFor(long, TimeUnit).
2) When the web socket is being closed parse the message in channel 3, if any, since this will contain the non-zero exit value of the exec.
3) Delay closing web socket streams until destroy() to resolve timing issue around reading from and closing these streams.
@brendanburns My fault getting the request for beta3 release and this change confused in order.  I initially requested beta3 thinking that exec would work fully and then realizing I could contribute the improvements.  If possible, and if this change is approved, please hold beta3 so that this can be included.  Thanks!
Note: I still can't resolve the the fact that the API server returns 400 Bad Request any …
=> Exec improvements to read non-zero exit code and implement waitFor(long, TimeUnit)

kubernetes/src/main/java/io/kubernetes/client/JSON.java
Apply the bytes array handling fix from
https://github.com/swagger-api/swagger-codegen/pull/7473
Fixes #131
=> Fix up byte array handling.

util/src/main/java/io/kubernetes/client/Exec.java
Fixes #225, though I would argue this is a breaking change for Kubernetes 1.9 and 1.10.
I'm going to try to repro and file a bug on upstream...
Sorry for the big diff. I also stripped `\r\n` from the file, I can revert for a cleaner diff if that is preferred.
The key diff is:
```java
+            + "&stdout=true"
+            + "&stderr=true"
```
in `Exec.java`
@rjeberhard
=> Add default true to stdout and stderr on Exec.

util/src/main/java/io/kubernetes/client/util/Yaml.java, util/src/test/java/io/kubernetes/client/util/YamlTest.java
There are some issues with the way the Yaml class auto-detects the Kubernetes object during the `load` function.
Commit `9e0b3b8` fixes a bug where the Apps Api is checked in the wrong order.
Commit `dd93b9d` auto-detects in a different way to include more of the available Api groups.
Commit `5a0439c` attempts to temporarily address the issue #221 where some classes have not been prefixed with their Api groups, until the class names have been generated properly.
See `dd93b9d`'s commit message for a list of Api prefixes that are missing from class names.
Keep what you want
=> Changes to the Yaml object auto-detection

util/src/main/java/io/kubernetes/client/util/Yaml.java, util/src/test/java/io/kubernetes/client/util/YamlTest.java, util/src/test/resources/test.yaml
- adding Yaml.loadAllAs() method to support multi yaml documents from single file. issue https://github.com/kubernetes-client/java/issues/254
- Moved static org.yaml.snakeyaml.Yaml(new CustomConstructor()) to getSnakeYaml() as, loading(loadAll)  multi yaml file using static snake yaml object and again using same static snake yaml object to instantiate the individual objects (org.yaml.snakeyaml.Yaml.loadAs()) is causing the Iterable to loose next element and causes null pointer exceptions.
- methods added:
* List<Object> loadAllAs(String content)
* List<Object> loadAllAs(File f)
* List<Object> loadAllAs(Reader reader)
=> add Yaml.loadAll() method

kubernetes/pom.xml, kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java, kubernetes/src/test/java/io/kubernetes/client/custom/IntOrStringTest.java
Implemented equals() and hash() for the IntOrString class. Unit test included
=> Support equals() for IntOrString

util/src/main/java/io/kubernetes/client/util/Watch.java
Improves behavior for #275 
@bartebor
=> Add a warning and an exception if a watch is created with debugging enabled.

examples/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, util/pom.xml
* fixes #291 
* added maven-bundle-plugin
* changed packaging to bundle to generate osgi manifests
* moved plugins to pluginManagement to have common versions
* removed duplicate jar goal in client-java-api
Plugin version upgrade:
* javadoc-plugin -> 3.0.1
* source-plugin -> 3.0.1
* release-plugin -> 2.5.3
* compiler-plugin -> 2.5.3
* compiler-plugin -> 3.7.0
* build-helper-maven-plugin -> 3.0.0
* jar-plugin -> 3.1.0
* surefire-plugin -> 2.22.0
* deploy-plugin -> 2.8.2
=> Added OSGi support and updated plugins #291

util/src/main/java/io/kubernetes/client/util/Yaml.java
Now, Yaml class uses SystemClassLoader for reflection.
If this library is  loaded by an another class loader.
SystemClassLoader doesn't know Yaml class.
Therefore`cp.getTopLevelClasses("io.kubernetes.client.models");` returns an empty list.
=> Avoid use SystemClassLoader on Yaml.

kubernetes/build.gradle, kubernetes/pom.xml, kubernetes/src/main/java/io/kubernetes/client/fluent/Config.java, kubernetes/src/test/java/io/kubernetes/client/models/V1PodBuilderTest.java
This pull request introduces fluent builders for all generated types (using [1]).
Swagger generated code still is unaware of these builders and is still using the setters. 
IMHO, it would make sense for the model objects to be immutable (or the builders don't have any real value), but that is something that would require a custom swagger extension/generator.
If there is concensus that this is the way to go, I wouldn't mind adding such a swagger extention/generator to project that generates the builders [1].
[1]: https://github.com/sundrio/sundrio
=> feat (#137): Introduce builder generation.

examples/Dockerfile, examples/createPod.sh, examples/test.yaml
- updated docker file with latest examples snpashot jar 
- changed openjdk:8-alpine to openjdk:8-jre as  alpine some times causing tls handshake error when pulling image(inside minikube docker)
- added createPod.sh which  creates a pod and runs Example.java(list pods for all namespaces) on starting of pod
=> adding sample yaml to test examples.jar from with in a pod

README.md
The versions in the README.md which is shown as the top-level document when looking at the repository, were outdated. Users might use those outdated versions and run into problems which have been fixed in the meantime.
=> Update the versions used in the README to latest stable and beta

util/src/main/java/io/kubernetes/client/util/ClientBuilder.java, util/src/main/java/io/kubernetes/client/util/KubeConfig.java
Further fixes for #386 
This emulates the kubeconfig code found here:
https://github.com/kubernetes/client-go/blob/master/util/homedir/homedir.go
@yu-shiba
=> Expand HOME detection on Windows.

examples/src/main/java/io/kubernetes/client/examples/CopyExample.java, util/pom.xml, util/src/main/java/io/kubernetes/client/Copy.java
=> Add utilities for copying files.

kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java
in Quantity constructor. Avoid doing extra work.
We only need to call it once.
=> Remove extra `Quantity.fromString()` call

util/src/main/java/io/kubernetes/client/util/Yaml.java, util/src/test/java/io/kubernetes/client/util/YamlTest.java, util/src/test/resources/expected.yaml, util/src/test/resources/test.yaml
Fix failing `YamlTest.testLoadAllFile()`
by adding a `CustomRepresenter` for `Quantity` to `Yaml`.
The serialized Deployment YAML's resource requests won't necessarily be in the
same format as the original. But this PR prevents the serialization from
returning empty maps which is an improvement.
In the future, another PR can be made which could guarantee the original YAML
is returned when serializing Deployment back to YAML.
=> Fix Quantity serialization

util/src/main/java/io/kubernetes/client/ProtoClient.java
`ProtoClient.update(...)` uses PUT, but really, it replaces the existing resource with the given name by the resource passed as parameter `obj`. It shouldn't have been named `update`, but instead, it should have been named `replace` for clarity. 
[reference](https://kubernetes.io/docs/reference/federation/v1/operations/#_replace_the_specified_service)
I didn't rename it regardless, because it would be a breaking change, but I did add the `merge(...)` method which uses `PATCH`, as I think it would be better to avoid using the `request(...)` method as much as possible for clarity.
=> Add merge in ProtoClient

kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java
Handles properly null quantities instead of throwing `NullPointerException`s. 
Fixes https://github.com/kubernetes-client/java/issues/441.
=> Fix serialization of null quantities

util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
@brendanburns, @1u0
Fix for https://github.com/kubernetes-client/java/issues/386#issuecomment-443705370
Ref #386, #390
=> NPE System.getenv(ENV_HOME) returns null on Windows

util/pom.xml
I'm trying to use the Java client in an OSGi application, which is failing as the Java client library has a dependency on the `com.microsoft.aad.adal4j` package.  This package cannot be found as `com.microsoft.azure:adal4j` dependency does not carry OSGi metadata.
But since this library is only required to use the Azure authenticator, we should mark this dependency as optional, which also marks the `com.microsoft.aad.adal4j` package dependency as optional too.
(This PR also fixes some stray tabs.)
=> Mark com.microsoft.azure.adal4j optional

util/src/main/java/io/kubernetes/client/util/ClientBuilder.java, util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
Use first kubeconfig file.
Kubectl documentation: 
https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#linux-1
=> Added support for KUBECONFIG environment variable with multiple paths.

pom.xml, util/src/main/java/io/kubernetes/client/util/ClientBuilder.java, util/src/main/java/io/kubernetes/client/util/Config.java, util/src/main/java/io/kubernetes/client/util/KubeConfig.java, util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java
Implementation of #238 allowing `~/.kube/config` to use the new generic exec credentials rather than a vendor-specific plugin or hard-coded token.
Planning to do before taking out of “draft” status:
Other things which I think could be left for follow-ups depending on demand:
=> #238: support client.authentication.k8s.io/v1beta1 ExecCredential

util/src/main/java/io/kubernetes/client/pager/Pager.java, util/src/test/java/io/kubernetes/client/pager/PagerTest.java
/cc @brendandburns 
Before this pull, `Pager` is not thread-safe. By adding a private non-static iterator class to store the pagination progress, the pager can be shared across threads now. Refactored the test a bit for validation.
=> Feat: Provide thread-safety for pager

kubernetes/pom.xml
For a project i'm working on, I need to update Swagger annotation library to 1.5.22.
Let me know if this will be an issue,
Derek
=> Update Swagger Annotation library to 1.5.22

extended/src/main/java/io/kubernetes/client/extended/wait/Wait.java, extended/src/main/java/io/kubernetes/client/extended/workqueue/DefaultDelayingQueue.java, extended/src/main/java/io/kubernetes/client/extended/workqueue/DefaultRateLimitingQueue.java, extended/src/main/java/io/kubernetes/client/extended/workqueue/DefaultWorkQueue.java, extended/src/main/java/io/kubernetes/client/extended/workqueue/DelayingQueue.java, extended/src/main/java/io/kubernetes/client/extended/workqueue/RateLimiter.java, extended/src/main/java/io/kubernetes/client/extended/workqueue/RateLimitingQueue.java, extended/src/main/java/io/kubernetes/client/extended/workqueue/WorkQueue.java, extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultDelayingQueueTest.java, extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultRateLimitQueueTest.java, extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultWorkQueueTest.java
ref [#523](https://github.com/kubernetes-client/java/issues/523).
Need more tests.
=> add workqueue implementation for kube-style controller

examples/src/main/java/io/kubernetes/client/examples/InformerExample.java, util/pom.xml, util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java, util/src/main/java/io/kubernetes/client/util/CallGenerator.java, util/src/test/java/io/kubernetes/client/informer/SharedInformerFactoryTest.java
this pull adds a new interface `CallGenerator` replacing `Function<CallGeneratorParam, Call>` to throw a checked `ApiException`. it's meaningless to handle the `ApiException` in the lambda body, the informer will deal w/ that. 
NOTE: this is breaking backward-compatibility a bit, while informer framework is still alpha, it's probably okay to make some minor adjustments.
/cc @brendandburns
=> [Refactor] Add Call-generator interface throwing checked ApiException

util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java, util/src/main/java/io/kubernetes/client/informer/cache/Cache.java, util/src/main/java/io/kubernetes/client/informer/cache/Caches.java, util/src/main/java/io/kubernetes/client/informer/cache/Lister.java, util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java, util/src/test/java/io/kubernetes/client/informer/cache/CacheTest.java, util/src/test/java/io/kubernetes/client/informer/cache/CachesTest.java
for now, we are only allowed to use `<namespace>` index funcs, this pull enables users to add customized index func. e.g. (as the test shown), for indexing pods, not only we can index by pod's namespace but also pod's nodeName from the spec:
1. Moves static helpers from `Cache` to `Caches`. note that we're deprecating the former and left a `TODO` noting it's gonna be removed after 7.0.0 release
2. Add more constructors to informer so that we can inject customized cache.
=> Refactor: Add constructor for customizing index funcs

examples/src/main/java/io/kubernetes/client/examples/LeaderElectionExample.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/ConfigMapLock.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/EndpointsLock.java
1. Show exception message when failing to acquire or renew election lock. Recently an exception thrown from the `tryAcquireOrRenew` is not logged.
2. Improve the argument of leader election example.
3. Add a TODO to remind to update lock with retry.
=> show exception message when failing to acquire or renew election lock

util/src/main/java/io/kubernetes/client/ProtoClient.java, util/src/main/java/io/kubernetes/client/util/SSLUtils.java
Hello,
updated ProtoClient to encode in hex not equal magic value, direct concatenation will lead to values like "I@4fee666" which aren't very helpful.
Noticed that in SSLUtils.loadDefaultStoreFile file input stream is not closed after loading of the file to keystore - added java 8 file closing.
=> Magic exception message update + FileInputStream closing in SSLUtils 

util/src/main/java/io/kubernetes/client/informer/cache/DeltaFIFO.java, util/src/test/java/io/kubernetes/client/informer/cache/DeltaFIFOTest.java
picking the informer fix from https://github.com/kubernetes/kubernetes/pull/83911
=> Bugfix(informer): DeltaFIFO Replace method to prevent SharedIndexInformers from missing notifications

util/src/main/java/io/kubernetes/client/util/Reflect.java
so that developers can inherit from the generated classes w/o breaking the informer framework..
=> Replace getDeclaredMethod vs getMethod to access parent class

extended/pom.xml, pom.xml, util/pom.xml
otherwise dependent will have trouble hitting exception:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/collections4/MapUtils
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections4.MapUtils
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 2 more
```
=> Pin commons-collections dependency 

extended/src/main/java/io/kubernetes/client/extended/controller/Controllers.java, extended/src/main/java/io/kubernetes/client/extended/pager/Pager.java, util/src/main/java/io/kubernetes/client/informer/cache/Caches.java, util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java, util/src/main/java/io/kubernetes/client/util/ListAccessor.java, util/src/main/java/io/kubernetes/client/util/ObjectAccessor.java, util/src/main/java/io/kubernetes/client/util/Reflect.java
separating these util functions helps us sorting them by their usages. and also this aligns w/ the naming from upstream client-go so that users can find them more easily.
=> Chore: Split reflect utils to [Object|List]accessor for clarification

kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java
This fix addresses #809 by declaring the inner class `QuanitytAdapter` static, similar to how `IntOrString` does. This allows it to be referenced in the GraalVM native-image reflection configuration in the same way.
Built and tested using `mvn install`. All tests passed (or were skipped):
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Kubernetes Client API 7.0.0-SNAPSHOT:
[INFO] 
[INFO] Kubernetes Client API .............................. SUCCESS [  0.092 s]
[INFO] client-java-api .................................... SUCCESS [08:28 min]
[INFO] client-java-proto .................................. SUCCESS [ 25.205 s]
[INFO] client-java ........................................ SUCCESS [03:39 min]
[INFO] client-java-extended …
```
=> declare QuantityAdapter static

util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
The current API of SharedInformerFactory supports two cases
in regards to the thread pool it uses inside:
1. Default thread pool - if no thread pool is specified, a new
thread pool is instantiated internally.
2. Provided thread pool - if a thread pool is specified, it
is the one used internally by this class.
Seems that the purpose of (2) is to enable users to provide
their own thread pool, configured the way they want rather than
relying on the thread pool that is instantiated internally.
However, one may think that (2) also enables the caller to pass
a thread pool that is shared among other components in their
application. The issue is that when calling the method
stopAllRegisteredInformers, it shuts down the thread pool and
that may not necessarily be the desired behavior in this case. …
=> Extract thread pool shutdown to a separate method

util/pom.xml
Fixes #811. Build and test using `mvn install`:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Kubernetes Client API 7.0.0-SNAPSHOT:
[INFO] 
[INFO] Kubernetes Client API .............................. SUCCESS [  0.137 s]
[INFO] client-java-api .................................... SUCCESS [08:28 min]
[INFO] client-java-proto .................................. SUCCESS [ 30.305 s]
[INFO] client-java ........................................ SUCCESS [07:44 min]
[INFO] client-java-extended ............................... SUCCESS [01:59 min]
[INFO] client-java-examples ............................... SUCCESS [ 10.398 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] …
```
=> update snakeyaml to 1.25

kubernetes/src/main/java/io/kubernetes/client/custom/V1Patch.java
Fixes #832 
This is a mirror of PR #810, which addressed a similar issue (#809) In the QuanittyAdapter. I missed that the same issue affected V1PatchAdapter as well. This applies the same fix and was verified with a modified version of the test program from #809. I grepped for any other instances of "extends TypeAdapter" without the static declaration and found none in the client code (there are some in the OpenAPI generated files types not used by Kubernetes AFAICT, which would have to be addressed upstream).
Build and test results:
```[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Kubernetes Client API 8.0.1-SNAPSHOT:
[INFO] 
[INFO] Kubernetes Client API .............................. SUCCESS [  0.123 s]
[INFO] client-java-api …
```
=> V1PatchAdapter should be declared static

util/src/main/java/io/kubernetes/client/informer/cache/Cache.java, util/src/main/java/io/kubernetes/client/informer/cache/Indexer.java, util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java, util/src/test/java/io/kubernetes/client/informer/cache/CacheTest.java
Implements `addIndexers` by modifying the `Indexer` interface to match `client-go`.  The semantics of `addIndexers` remains consistent with `client-go` as well.
References:
1) https://github.com/kubernetes/client-go/blob/master/tools/cache/shared_informer.go#L362
2) https://github.com/kubernetes/client-go/blob/master/tools/cache/index.go#L48
3) https://github.com/kubernetes/client-go/blob/master/tools/cache/thread_safe_store.go#L228
=> Implement DefaultSharedIndexInformer#addIndexers

extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java, extended/src/main/java/io/kubernetes/client/extended/generic/KubernetesApiResponse.java, extended/src/main/java/io/kubernetes/client/extended/generic/options/CreateOptions.java, extended/src/main/java/io/kubernetes/client/extended/generic/options/DeleteOptions.java, extended/src/main/java/io/kubernetes/client/extended/generic/options/GetOptions.java, extended/src/main/java/io/kubernetes/client/extended/generic/options/ListOptions.java, extended/src/main/java/io/kubernetes/client/extended/generic/options/PatchOptions.java, extended/src/main/java/io/kubernetes/client/extended/generic/options/UpdateOptions.java, extended/src/test/java/io/kubernetes/client/extended/generic/FooCustomResource.java, extended/src/test/java/io/kubernetes/client/extended/generic/FooCustomResourceList.java, extended/src/test/java/io/kubernetes/client/extended/generic/GenericKubernetesApiTest.java, extended/src/test/java/io/kubernetes/client/extended/generic/GenericKubernetesGetApiTest.java
@brendandburns 
NOTE: i will sanitize the pull l8r (the license, formatting, etc..).. 
it's neat and simple. w/ the help of this generic client, what we only need is the generated model. i just drafted initial version of code and test, it already covers all the api paths on the kubernetes apiserver.
the general idea is to make use of CustomObjectApi as best as we can, this will help us access custom resources in kubernetes in an easier way. appreciated if you feel like shed some light on it
=> Generic kubernetes api client

util/src/main/java/io/kubernetes/client/Attach.java, util/src/main/java/io/kubernetes/client/Exec.java, util/src/test/java/io/kubernetes/client/AttachTest.java, util/src/test/java/io/kubernetes/client/ExecTest.java
Resolves #847.
The basic idea is to express options for Attach and Exec like:
```
attach
.prepare(namespace, name)
.setStdout(true)
.setTty(true)
.connect();
```
=> Builder-modes for attach() and exec()

extended/pom.xml, extended/src/main/java/io/kubernetes/client/extended/workqueue/ratelimiter/BucketRateLimiter.java
Hello guys,
As the author of Bucket4j, I had done review the usage of my library in the kubernatess-client/java and me found that code can be reduced a lot if upgrade from ```4.4.1``` to ```4.8.0```.
=> Simplify usage of Bucket4j via using new API method consumeIgnoringRateLimits which was added in the version 4.8.0

README.md, examples/pom.xml, examples/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java, spring/pom.xml, spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java
=> Adding example for spring-based controller construction

examples/src/main/java/io/kubernetes/client/examples/GenericClientExample.java, extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java
=> Generic kubernetes api example

util/src/main/java/io/kubernetes/client/Exec.java
Kubelet is actually exposing a set of channels in the exec webconnection:
0. stdin
1. stdout
2. stderr
3. kubelet connection error
4. resizing 
this pull adds access for the last two channel
/cc @brendandburns
=> Feat: Implementing resizable/error exec stream

util/src/main/java/io/kubernetes/client/Exec.java, util/src/test/java/io/kubernetes/client/ExecTest.java
Fix for Issues #861, #908 and #928
2nd approach to fix the above issues.
Replaced wait/notify with countdown latch and initiated WebSocket closure from the client-side.
=> Approach 2 - Fix for non closure of input stream for Copy utility

extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java
1. fixes a bug that patch method on generic kubernetes api doesn't receive custom apicilent properly
2. fall-fast (throw a runtimeexception) on unrecognized exception.
=> Fixes generic kubernetes api patches

examples/pom.xml, extended/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring/pom.xml, util/pom.xml
since the 1.17 codegen PR merged, move to a new major release version.
=> Move to version 9.0.0 for 1.17 Kubernetes API.

util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
defaulting protocols in the client builder to HTTP1.1 otherwise when connecting latest kubernetes apiservers all the examples will fail w/ the following traces:
```
Exception in thread "main" io.kubernetes.client.openapi.ApiException: okhttp3.internal.http2.ConnectionShutdownException
at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:898)
at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:18981)
at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:18953)
at io.kubernetes.client.examples.Example.main(Example.java:39)
Caused by: okhttp3.internal.http2.ConnectionShutdownException
at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:242)
at …
```
=> Defaulting okhttp client protocols to HTTP1.1

examples/pom.xml, extended/pom.xml, pom.xml, proto/pom.xml, spring/pom.xml, util/pom.xml
before this pull, the dependency versions are separated in the sub-modules and there're even conflicting versions.. this is pull does the following things:
- converges dependency definitions from non-generated modules into parent pom's <dependencyManagement> tag
- merges all properties from non-generated modules into parent pom
=> Chore: Pom clean up and merges properties/versions definitions to parent pom

examples/src/main/java/io/kubernetes/client/examples/CopyExample.java, util/src/main/java/io/kubernetes/client/Copy.java, util/src/main/java/io/kubernetes/client/util/exception/CopyNotSupportedException.java
Right now copy method throws runtime error if Tar is not present in the target container. Added a check for it before proceeding with copying process.
Note: This will only work for the containers which has POSIX based underlying image
=> Adding a check to test if Tar utility is present in the target container

docs/generate-model-from-third-party-resources.md
=> Revise CRD generation guides: uses generator script instead of running images

extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java, extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectionTest.java, util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java, util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
the exception handlers for reflector is already supported in the golang client library https://github.com/kubernetes/kubernetes/pull/87329. this pull implements similar capabilities for both reflector and leader-electors..
=> Reflector and leader-elector exception handlers

extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/exception/KubectlException.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlLabelTest.java, util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java, util/src/main/java/io/kubernetes/client/util/labels/Labels.java, util/src/test/java/io/kubernetes/client/util/labels/LabelsTest.java
this pull initiates a new set of helper classes under extended module providing similar capabilities w/ kubectl commands:
```
V1Pod labelledPod =
Kubectl.label(apiClient, V1Pod.class)
.apiGroup("")
.apiVersion("v1")
.resourceNamePlural("pods")
.namespace("default")
.name("foo")
.addLabel("k1", "v1")
.addLabel("k2", "v2")
.execute();
```
=> Kubectl label equivalence

extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java, extended/src/main/java/io/kubernetes/client/extended/controller/DefaultControllerWatch.java, spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java, spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerWatch.java, spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerCreatorTest.java, util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java
resolves https://github.com/kubernetes-client/java/issues/1108
in order to support mapping one resource event to multiple controller-requests, we made the following adjustment to the controller framework:
- support returning a `null` request from the work-queue-key-func so that it can optionally be silent/no-op at some time
- (for spring integration) support receiving `WorkQueue` instance in the constructor of the work-queue-key-func so it can now manually push multiple controller-requests to the work-queue upon resource events (for sample, see the tests in this pull)
as for [non-spring construction](https://github.com/kubernetes-client/java/blob/894b1631e83d23a65440060b341faeba58c66760/examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java#L90-L92) of controllers, …
=> Support custom workqueue-keyfunc to directly manipulate work-queue instance

extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlExec.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlScale.java
Get rid of force type casting by adding type parameter to ResourceBuilder.
follow-up of #1135
=> Refactor(kubectl): get rid of force api type class casting

util/src/main/java/io/kubernetes/client/informer/cache/SharedProcessor.java, util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java, util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java, util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java
Once this is merged, I will generate/push the release.
=> Cherry pick some fixes to set the stage for 9.0.1

util/src/main/java/io/kubernetes/client/Copy.java, util/src/main/java/io/kubernetes/client/TreeNode.java, util/src/test/java/io/kubernetes/client/CopyTest.java
This is related to #1091 .If `tar` is not present in target container, then the code will fall back to copying individual files using `cat`. There are few TODO comments for me to address in more PRs after this.
=> Supporting copy operation when tar is not present

examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlAnnotate.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlApiResources.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCopy.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlExec.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLog.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPortForward.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlScale.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlTaint.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlVersion.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlAnnotateTest.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlLabelTest.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlScaleTest.java
move those redundant `KubectlXXX(ApiClient)` entry methods to a `ApiClientBuilder` abstract base class to share more codes
=> Refactor: Share more codes between kubectl entry methods

pom.xml, util/pom.xml, util/src/main/java/io/kubernetes/client/apimachinery/GroupVersionKind.java, util/src/main/java/io/kubernetes/client/apimachinery/GroupVersionResource.java, util/src/main/java/io/kubernetes/client/apimachinery/KubernetesRequestDigest.java, util/src/main/java/io/kubernetes/client/apimachinery/KubernetesResource.java, util/src/main/java/io/kubernetes/client/apimachinery/KubernetesVerb.java, util/src/main/java/io/kubernetes/client/apimachinery/ParseKubernetesResourceException.java, util/src/main/java/io/kubernetes/client/monitoring/PrometheusInterceptor.java
the new classes are picked from https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/651, except for those groovy unit tests..
a sample output from the prometheus example will be:
```
k8s_java_resource_request_latency_seconds_bucket{http_response_code="404",api_group="",api_version="v1",resource="pods",subresource="",api_verb="get",namespace="bar",le="0.005",} 0.0
k8s_java_resource_request_latency_seconds_bucket{http_response_code="404",api_group="",api_version="v1",resource="pods",subresource="",api_verb="get",namespace="bar",le="0.01",} 2.0
k8s_java_resource_request_latency_seconds_bucket{http_response_code="404",api_group="",api_version="v1",resource="pods",subresource="",api_verb="get",namespace="bar",le="0.025",} 2.0 …
```
=> Instrumenting follow-up: metrics labelling w/ finer granularity

README.md
I don't have a link at the moment, but IIRC, kubernetes masters only promise backwards compatibility of two versions of the API client, so running a version older than that may run into potholes of broken behavior as the master no longer supports a deprecated/removed API.
/cc @lavalamp
=> Amend Compatibility table to document n-2 version guarantees.

extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectionTest.java
=> Remove some sleeps in tests to deflake.

e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlApplyTest.groovy, e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlCreateTest.groovy, extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlGet.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlGetTest.java
ideally i think this can be a replacement for GenericKubernetesApi
=> Feat: Kubectl get implementation

util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java, util/src/main/java/io/kubernetes/client/informer/cache/DeltaFIFO.java, util/src/test/java/io/kubernetes/client/informer/cache/DeltaFIFOTest.java
reason: on timeout-reconnect it will add new a new copy to all objects in FIFO items map.
fix: check resourceVersion when adding object copy, skip if newly added object has same resourceVersion with previous latest object.
=> fix issue 912: do dedupe with resourceVersion

client-java-contrib/Dockerfile, client-java-contrib/Dockerfile.gen, client-java-contrib/Dockerfile.gen-base, client-java-contrib/cert-manager/update.sh, client-java-contrib/prometheus-operator/update.sh, client-java-contrib/publish-gen-image.sh, docs/generate-model-from-third-party-resources.md
making `docker.pkg.github.com/..` images public requires `kubernetes-client` admin access so i copied the images under my repository so that users can pull anonymously..
@brendandburns @kumars17
=> Provide base images for saving installation time

util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
Reflector Runnable is using timeout duration as millis value rather than seconds as mentioned in [api references](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#watch-deployment-v1-apps).
@brendanburns @yue9944882
=> reflector: fix watch timeout by using it as seconds unit

examples/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java
=> Trim controller example based on controller auto-configuration

README.md, examples/examples-release-last
sadly the symlink doesn't work on the github README page.. revert the symlink path to the actual module path
=> Doc: Use module name directly instead of symlink

spring/src/main/java/io/kubernetes/client/spring/extended/manifests/KubernetesKubectlApplyProcessor.java, spring/src/main/java/io/kubernetes/client/spring/extended/manifests/annotation/KubectlApply.java, spring/src/main/java/io/kubernetes/client/spring/extended/manifests/config/KubernetesManifestsAutoConfiguration.java, spring/src/test/java/io/kubernetes/client/spring/extended/manifests/KubernetesManifestTest.java
KubectlCreate is good if things are constant, but if resources could have changed, it's useful to perform an apply instead.
Note that this is largely, copy/paste from KubectlCreate, we could consider extracting a super-class for shared methods if we wanted to.
=> Add a KubectlApply processor for Spring.

pom.xml, util/pom.xml, util/src/main/java/io/kubernetes/client/Copy.java
Cherry-pick #1426 into the 9.0.x release branch.
=> Cherry-pick #1426

extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlApplyTest.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlCreateTest.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlDrainTest.java, extended/src/test/java/io/kubernetes/client/extended/pager/PagerTest.java, pom.xml, spring/src/test/java/io/kubernetes/client/spring/extended/manifests/KubernetesManifestTest.java, util/src/test/java/io/kubernetes/client/ExecTest.java, util/src/test/java/io/kubernetes/client/PodLogsTest.java, util/src/test/java/io/kubernetes/client/Resources.java, util/src/test/java/io/kubernetes/client/informer/cache/DeltaFIFOTest.java, util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java, util/src/test/java/io/kubernetes/client/util/FilePersisterTest.java, util/src/test/java/io/kubernetes/client/util/SSLUtilsTest.java, util/src/test/java/io/kubernetes/client/util/YamlTest.java, util/src/test/java/io/kubernetes/client/util/credentials/ClientCertificateAuthenticationTest.java, util/src/test/java/io/kubernetes/client/util/credentials/OpenIDConnectAuthenticationTest.java, util/src/test/java/io/kubernetes/client/util/credentials/TokenFileAuthenticationTest.java, util/src/test/java/io/kubernetes/client/util/credentials/UsernamePasswordAuthenticationTest.java
There was a regex in the spotless config in top level pom.xml designed to assert that Guava was not being used, but the pattern was wrong. Once you fix that, you either need to rewrite some of the tests that were still using it, or don't apply that rule to tests.
=> Fix Guava regexp in spotless config

e2e/src/test/groovy/io/kubernetes/client/e2e/basic/CoreV1ApiTest.groovy, kubernetes/src/main/java/io/kubernetes/client/gson/V1StatusPreProcessor.java, kubernetes/src/main/java/io/kubernetes/client/openapi/JSON.java, kubernetes/src/test/java/io/kubernetes/client/gson/V1StatusJsonDeserializerTest.java
Fixes: https://github.com/kubernetes-client/java/issues/86
this pull will be suppressing the GsonSyntaxException on deletion by adapting non-status resources into status during deserialization.
@brendandburns i think we should get this into 11.0.x releases.
=> Workaround for gson-syntax-exception upon deletion even if the deletion succeeds

extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/ConfigMapLock.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/EndpointsLock.java, extended/src/test/java/io/kubernetes/client/extended/controller/LeaderElectingControllerTest.java, extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectionTest.java, extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectorTest.java, extended/src/test/java/io/kubernetes/client/extended/leaderelection/LockSmith.java
So that other candidate can become the next leader quickly or else other candidate might need to wait for full `leaseDuration` before getting the lock.
=> Leader to give up leadership lock on graceful shutdown

e2e/pom.xml, e2e/src/test/java/io/kubernetes/client/e2e/extended/leaderelection/LeaderElectorTest.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/LeaseLock.java
follow up #1460
these tests also exercise all different Lock implementations.
=> leaderelection sanity e2e integration tests

util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java, util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java
Fixes #1442, as a draft at least. We could refactor it to be more like the Golang API, e.g. 
```java
GenericKubernetesApi<T,L> api = ...;
api.status().update(...);
```
instead of
```java
GenericKubernetesApi<T,L> api = ...;
api.updateStatus(...);
```
WDYT?
=> Add updateStatus() convenience methods to GenericKubernetesApi

e2e/src/test/java/io/kubernetes/client/e2e/extended/leaderelection/LeaderElectorTest.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/LeaseLock.java, kubernetes/src/main/java/io/kubernetes/client/openapi/JSON.java, kubernetes/src/test/java/io/kubernetes/client/openapi/JSONTest.java
@brendandburns @dsyer 
it's a follow-up of #1418.
this pull will force the timestamp types to be serialized including 6 digit of fraction in order to support the precision of micro-second.
the original kubernetes go types basically accepts two kinds of timestamp in RFC3339:
1. `RFC3339     = "2006-01-02T15:04:05Z07:00"` for the go type [metav1.Time](https://github.com/kubernetes/kubernetes/blob/39483aa0957be65b04686173d2970b508b3974ca/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/time.go#L31-L33)
2. `RFC3339Micro = "2006-01-02T15:04:05.000000Z07:00"` for the go type [metav1.MicroTime](https://github.com/kubernetes/kubernetes/blob/39483aa0957be65b04686173d2970b508b3974ca/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time.go#L31-L33)
at the kubernetes server side, (2) can be …
=> Support rfc3339 micro-sec (6 digit) timestamp

.github/workflows/maven.yml, examples/examples-release-11/pom.xml, examples/examples-release-12/pom.xml, examples/pom.xml
TBH I'm not sure why there are 3 sets of examples, or why they 
are all in the same project/package. But there appears to have been
some rot because they are not included in CI. This attempts to fix
things.
=> Fix examples so they compile and tests are green

util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
Fixes https://github.com/kubernetes-client/java/issues/1370
=> Update client builder to be more robust by default

util/src/main/java/io/kubernetes/client/util/SSLUtils.java
This is the case on e.g. Android. BKS is BouncyCastles JKS-compatible implementation of a KeyStore
=> Fallback to BKS when JKS is not available

spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java, spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessorTest.java
With this change `KubernetesReconcilerProcessor` conforms to `BeanFactoryPostProcessor`
contract to register `BeanDefinitions` and not to manipulate bean instances.
As a result Reconciler beans are:
1) **not** created at all by `postProcessBeanFactory` (which was the core issue)
2) participate in Spring container management hooks, and hence `@Autowired`
=> Register ControllerFactory bean definition as opposite to bean instance

util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java, util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
Fixes: https://github.com/kubernetes-client/java/issues/1533
=> Fixes reflector list expiration

util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java, util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
Cherry-picks https://github.com/kubernetes-client/java/pull/1543 to release-11 branch.
=> Cherrypick for RELEASE-11: Fixes reflector list expiration

client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-10/pom.xml, examples/examples-release-11/pom.xml, examples/examples-release-12/pom.xml, examples/examples-release-12/src/main/java/io/kubernetes/client/examples/DynamicClientExample.java, examples/examples-release-12/src/main/java/io/kubernetes/client/examples/SpringLoadBalancerExample.java, examples/pom.xml, extended/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring/pom.xml, util/pom.xml
This will make IDEs work better (especially VSCode) because
otherwise they cannot compute the classpath for the examples.
=> Make Maven reactor build work

extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventLogger.java, extended/src/test/java/io/kubernetes/client/extended/event/legacy/EventLoggerTest.java
cc @chris-chambers @brendandburns
a follow-up of https://github.com/kubernetes-client/java/pull/1559#issuecomment-786150196
=> Fixes eventlogger timestamp format

extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventLogger.java, extended/src/test/java/io/kubernetes/client/extended/event/legacy/EventLoggerTest.java
cherry-picking https://github.com/kubernetes-client/java/pull/1559 and https://github.com/kubernetes-client/java/pull/1569 to release-11
=> Cherrypick for RELEASE-11: Fixes event-logger patch content

extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventLogger.java, extended/src/test/java/io/kubernetes/client/extended/event/legacy/EventLoggerTest.java
There was a cherry-pick of an event logger fix, but it was after the switch to OffsetDateTime which isn't present in the 11.0.x branch.
=> Fix the build for JODA time

util/src/main/java/io/kubernetes/client/util/generic/KubernetesApiResponse.java, util/src/test/java/io/kubernetes/client/util/generic/KubernetesApiResponseTest.java
Picking https://github.com/kubernetes-client/java/pull/1529 to 11.0.x branch
=> Cherrypick for RELEASE-11: Passing actual response status code in error-handler

e2e/src/test/java/io/kubernetes/client/e2e/extended/leaderelection/LeaderElectorTest.java
in the flaking e2e test, the original timeout is 30s and meanwhile the `leaseDuration=30s` and `retryInterval=5s`. so the lock competitors are jittered by `(jitter_factor (0~1.2) + 1) * 5s <= 11s` hence extending the timeout margin w/ 15s will easing the flakiness
=> Flake: Fixes leader-election e2e flakiness by relaxing timeout to 45s

spring/pom.xml, spring/src/main/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromConfigMapProcessor.java, spring/src/main/java/io/kubernetes/client/spring/extended/manifests/annotation/FromConfigMap.java, spring/src/main/java/io/kubernetes/client/spring/extended/manifests/config/KubernetesManifestsAutoConfiguration.java, spring/src/main/java/io/kubernetes/client/spring/extended/manifests/config/KubernetesManifestsProperties.java, spring/src/main/java/io/kubernetes/client/spring/extended/manifests/configmaps/ConfigMapGetter.java, spring/src/main/java/io/kubernetes/client/spring/extended/manifests/configmaps/InformerConfigMapGetter.java, spring/src/main/java/io/kubernetes/client/spring/extended/manifests/configmaps/PollingConfigMapGetter.java, spring/src/test/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromConfigMapTest.java
example usage:
```java
public class App {
@FromConfigMap(namespace="default", name="my-config")
private Map<String, String> myConfig;
}
```
=> Feat(spring): Adding FromConfigMap annotation that dynamically maps data config-map to map

spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java, spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java, spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerProperties.java, util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
https://github.com/kubernetes-client/java/blob/d9271d47aa6f00e7e28b3df3281ef4f282442acb/spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java#L95-L96
these lines were dropped during refactoring informer-processor and this pull adds it back. tho this can workaround by explicitly setting the read-timeout to zero upon instanciating the ApiClient bean.
/cc @brendandburns @dsyer
=> Enforcing read-timeout for informer-factory processor via property "kubernetes.informer.clientReadTimeout" (default 5min)

e2e/pom.xml
Improves logging for e2e tests.
Ref #1480
=> Add logging dependency to e2e tests.

extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlGet.java
Fix the problem of getGenericApi failure when the `KubectlGetSingle.execute()` method is executed for the first time
=> bugfix KubectlGetSingle.execute() error

util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java, util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
In the pull https://github.com/kubernetes-client/java/pull/1543, we added catcher for intercepting 410 status code but the non-410 errors will be missing. this pull makes the reflector properly handles the non-410 codes.
=> Bugfix: Properly handling non-410 ApiExcetion in the reflector

spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerProperties.java, util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
@cizezsy 
Fixes: #1648 
following prior art from https://github.com/kubernetes/kubernetes/blob/898bb9666c866515aa8d51227759ee757a11f262/staging/src/k8s.io/client-go/tools/cache/reflector.go#L143-L144
=> Feat: Jittering informer client-side watch timeout between 5~10 minutes

kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java
unless we figure out how to efficiently update the version string (`11.0.1-SNAPSHOT`) somehow..
=> Chore: Removing version from default user-agent header

examples/examples-release-12/pom.xml, examples/examples-release-13/pom.xml
The samples will not log anything when they run without a logging
library. Logback is only in test scope because of the parent pom
(I think). So we need to add it back explicitly.
=> Added explicit runtime dependency for logback

examples/examples-release-12/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java, examples/examples-release-13/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java
This fix is masking another problem somewhere else, but at least it gets
the apps working while we investigate.
Fixes #1684 (temporarily at least). Also rebased on #1685.
=> Fix SpringExampleController so it doesn't crash on startup

spring/src/main/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromConfigMapProcessor.java, spring/src/main/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromYamlProcessor.java
@brendandburns in https://github.com/kubernetes-client/java/issues/1638, the spring module is constantly failing due to bumping platform to java 16. this pull will eliminating the impact for those who are not actually using `@FromYaml` or `@FromConfigMap` annotation from spring integration. and we will also a follow-up pull to completely fix the compatibility issue for the annotations.
=> Java 16 compatibility pt1: Reducing inaccessibility impact

pom.xml
Bumps `bouncycastle.version` from 1.66 to 1.68.
Updates `bcprov-ext-jdk15on` from 1.66 to 1.68
- [Release notes](https://github.com/bcgit/bc-java/releases)
- [Changelog](https://github.com/bcgit/bc-java/blob/master/docs/releasenotes.html)
- [Commits](https://github.com/bcgit/bc-java/commits)
Updates `bcpkix-jdk15on` from 1.66 to 1.68
- [Release notes](https://github.com/bcgit/bc-java/releases)
- [Changelog](https://github.com/bcgit/bc-java/blob/master/docs/releasenotes.html)
- [Commits](https://github.com/bcgit/bc-java/commits)
Signed-off-by: dependabot[bot] <support@github.com>
=> Cherry pick 11: Bump bouncycastle.version from 1.66 to 1.68

.github/workflows/maven.yml, spring/pom.xml, util/pom.xml, util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java
@yue9944882 I think we shouldn't test/support Java versions that are no longer supported by the Java team.
=> Revise the Java versions we test to LTS + latest non-LTS version.

extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPatch.java
… (#1631)
* bugfix KubernetesApiResponse cannot be cast to class KubernetesObject
* fix source code format
* update catch ApiException
(cherry picked from commit 0f78b732927075c1d57a670f53ea08efde2ce892)
=> Cherry-pick of #1631 into Release-12

extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPatch.java
… (#1631)
* bugfix KubernetesApiResponse cannot be cast to class KubernetesObject
* fix source code format
* update catch ApiException
(cherry picked from commit 0f78b732927075c1d57a670f53ea08efde2ce892)
=> Cherry-pick of #1631 into Release-11

util/src/test/java/io/kubernetes/client/informer/cache/ControllerTest.java
=> Reduce controller test flakiness by distinguishing resource-versions

util/src/main/java/io/kubernetes/client/util/Yaml.java, util/src/test/java/io/kubernetes/client/util/YamlTest.java, util/src/test/resources/crd-int-or-string.yaml
Fixes: https://github.com/kubernetes-client/java/issues/1796
this pull allows the yaml serializer to have similar behavior as gson's `@SerializedName` annotation by registering additional type descriptions. 
and i will pick it to past releases after merged, as it's breaking all CRDs w/ the openapi extension.
cc @brendandburns
=> Bugfix: CRD's openapi schema extension cannot be properly serialized

util/src/main/java/io/kubernetes/client/util/authenticators/GCPAuthenticator.java, util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java, util/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Related Issues: 
- https://github.com/kubernetes-client/java/issues/290
- https://github.com/kubernetes-client/java/issues/1664
I wrote a "refresh" function because it seems to be using "cmd-path", "cmd-args", "expiry-key", "token-key" to refresh the token.
Need to check that it works on various os platforms.
=> support gcp authentication refresh token

util/src/main/java/io/kubernetes/client/util/authenticators/GCPAuthenticator.java, util/src/test/java/io/kubernetes/client/util/authenticators/GCPAuthenticatorTest.java
When trying to authenticate to GCP, the GCPAuthenticator composes a gcloud cmd where the args are added without empty spaces. See issue:
https://github.com/kubernetes-client/java/issues/1821
I wasn't sure about the code style. Unfortunately I couldn't find anything related to it.
=> Fix GCPAuthenticator to compose a correct command

util/src/main/java/io/kubernetes/client/util/okhttp/HTTP2ConsoleHandler.java, util/src/main/java/io/kubernetes/client/util/okhttp/HTTP2Logging.java
this pull introduces a new utility class `HTTP2Logging` which allows you to enable/disable logging for HTTP2 handshake & streams via the JUL library.
note that the original script is from https://square.github.io/okhttp/debug_logging/, this pull is just converting the kotlin cheatsheet to a static helper. a sample of logging is shown below:
```
[2021-08-11 15:24:20] Q10005 scheduled after  60 s : OkHttp 127.0.0.1 ping 
[2021-08-11 15:24:20] >> CONNECTION 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a 
[2021-08-11 15:24:20] >> 0x00000000     6 SETTINGS       
[2021-08-11 15:24:20] >> 0x00000000     4 WINDOW_UPDATE  
[2021-08-11 15:24:20] Q10008 scheduled after   0 µs: OkHttp 127.0.0.1 
[2021-08-11 15:24:20] Q10008 starting              : OkHttp 127.0.0.1 
[2021-08-11 15:24:20] Q10000 …
```
=> Additional debugging option for printing http2 frames

util/src/test/java/io/kubernetes/client/AttachTest.java
`InputStream.read()` blocks until input data is available, which makes sure the connection has been established.
=> Kill the sleep in AttachTest

util/src/main/java/io/kubernetes/client/Copy.java, util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java, util/src/test/java/io/kubernetes/client/CopyTest.java
Third time's the charm....
- Fix for #1826: Updated WebSocketStreamHandler.write() to calculate 'remaining' bytes using bufferSize from the current loop iteration instead of the cummulative bytesWritten.
- Related to #1822:  Removed the base64 encode/decode steps/streams per comment at https://github.com/kubernetes-client/java/issues/1822#issuecomment-900315846
- Related to #1822:  Added path normalization to convert potential windows path delimiters to linux delimiters.  The copyFileToPod() variants take a java Path instance for both source and destination.  Since the destination is Linux, when I set destPath = Paths.get("/tmp/foo.txt");, converting that to a string to send to the tar command ends up sending "\tmp" as the parentPath which is not valid for linux.
=> Updated WebSocketStreamHandler.write() to calculate 'remaining' bytes properly : Fixed destPath normalization for potential Windows delimiters

util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java, util/src/main/java/io/kubernetes/client/informer/exception/WatchExpiredException.java, util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
picking https://github.com/kubernetes-client/java/pull/1832 to release-13
cc @brendandburns @haoming-db 
i will bump a patch version after this gets into 13 branch
=> Cherry-pick(release-13): Stale watch event should be handled properly

extended/src/main/java/io/kubernetes/client/extended/pager/Pager.java
Fixes https://github.com/kubernetes-client/java/issues/1843#issuecomment-907548421
cc @NeverRaR  @dddddai @brendandburns
=> Bugfix: Move Pager's concurrently read fields to nested class

extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlApplyTest.java, util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java, util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiForCoreApiTest.java
Fix #1838
If `basePath` contains multiple segments (like using java client with rancher clusters), it would tweak the call incorrectly and break the request url, see https://github.com/kubernetes-client/java/issues/1838#issuecomment-913290787
So it should calculate the segment indexes to be modified instead of hardcoding them to 0 and 1.
=> Tweak call for CoreV1 group properly

extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPatch.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlPatchTest.java
Fix #1887
Attach `ApiType` to `KubectlPatch` in `patchContent` and `patchType`
=> Return specific api type in patchContent and patchType

client-java-contrib/Dockerfile.gen, client-java-contrib/Dockerfile.gen-base
Couple of issues with Dockerfiles in client-java-contrib:
The base image is a private image in Dockerfile.gen. It should take the base image as an argument with default values.
Dockerfile.gen-base is using variables and doesnt define them as arguments:
${OPENAPI_GENERATOR_USER_ORG}
OPENAPI_GENERATOR_COMMIT
Because of this the Dockerfile doesn't build.
https://github.com/kubernetes-client/java/issues/1897
=> Fix arguments to dockerfiles

util/src/main/java/io/kubernetes/client/Discovery.java
Issue: https://github.com/kubernetes-client/java/issues/1886
This code is added to have defense against null pointer exception in manageRelationFromResourceToSubResources method in discovery class
=> Guard against NPE in manageRelationFromResourceToSubResources from Discovery class

.github/workflows/maven.yml
picks https://github.com/kubernetes-client/java/pull/1876 to release-13 so that the branch's CI passes
=> Cherrypick-13: Test: Fixes constant maven download failure by escalating mvn permission

util/src/test/java/io/kubernetes/client/CopyTest.java
Fixes: https://github.com/kubernetes-client/java/issues/1862
=> Flake: Catching illegal-state-exception in the copy test

.github/workflows/maven.yml
https://github.com/actions/setup-java/blob/main/README.md
```
NOTE: Adopt OpenJDK got moved to Eclipse Temurin and won't be 
updated anymore. It is highly recommended to migrate workflows 
from adopt to temurin to keep receiving software and security updates.
```
=> chore: 'adopt' --> 'temurin'

extended/src/test/java/io/kubernetes/client/extended/controller/builder/DefaultControllerBuilderTest.java, extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultDelayingQueueTest.java, spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java
Fixes #2006 and #2013 (I hope)
=> De-flake a couple tests.

util/src/main/java/io/kubernetes/client/util/SSLUtils.java
=> support certificate chain when reading client certificate(s)

pom.xml, util/pom.xml, util/src/main/java/io/kubernetes/client/util/authenticators/GCPAuthenticator.java, util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java, util/src/test/java/io/kubernetes/client/util/authenticators/GCPAuthenticatorTest.java
https://github.com/kubernetes-client/java/issues/290#issuecomment-979515942
https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication#environments-without-gcloud
=> GCPAuthenticator support without gcloud

spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java
=> Return a default APIClient if we run into an exception

.github/workflows/snapshot.yml, README.md
@brendandburns i added my jira account credentials and gpg keys in the repo secrets to push snapshots. github claims that these secrets are perfectly protected 🤞
if this works well, we can move the maven release job as another job triggered by simple git tags. so we don't need to deal with the fiddly release process manually anymore!
=> gh-action: Upload snapshot as post-commit job

util/src/main/java/io/kubernetes/client/util/ModelMapper.java, util/src/test/java/io/kubernetes/client/util/ModelMapperTest.java
Fix `java.lang.ArrayIndexOutOfBoundsException` from YamlExample
Repro case:
```
../../mvnw exec:java -Dexec.mainClass="io.kubernetes.client.examples.YamlExample"
```
=> Fix arrayIndexOutOfBounds exception for overloaded addModelMap method

.github/workflows/release.yml, RELEASES.md
> Signed-off-by: yue9944882 <291271447@qq.com>
@brendandburns i also clarified the usage of the release job in the doc.
https://github.com/kubernetes-client/java/pull/2056 is an example of the generated commits by the job. as the next step, we can cherry-pick this release job to the recent release branches and send a release `11.0.4` for https://github.com/kubernetes-client/java/issues/2041
=> Adding an manual release job that applies to release branches publishing maven releases

.github/workflows/release.yml
resolving the failure from the partly successful release job from https://github.com/kubernetes-client/java/issues/2041#issuecomment-1007086605: 
> remote: error: GH006: Protected branch update failed for refs/heads/release-11.
remote: error: Required status check "cla/linuxfoundation" is expected.
To https://github.com/kubernetes-client/java.git
! [remote rejected] release-11 -> release-11 (protected branch hook declined)
error: failed to push some refs to 'https://github.com/kubernetes-client/java.git'
an example of the automated PR is https://github.com/yue9944882/java/pull/16
=> Release Action: Send PR instead of direct push

pom.xml, spring/pom.xml, spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java, util/pom.xml, util/src/main/java/io/kubernetes/client/util/Watch.java, util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java, util/src/test/java/io/kubernetes/client/util/ConfigTest.java, util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiForCoreApiTest.java, util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java, util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesGetApiTest.java
1. replacing `com.github.stefanbirkner/system-lambda` w/ `uk.org.webcompere/system-stubs-core`, which is a dropin replacement for the former library that fixes the environment issue.
2. adding a default contructor for `Watch#Response` to avoid gson's reflective dynamic constructor which violates the jdk16 restriction.
=> Fixes java 16 compability

.github/workflows/release.yml
When I did the release, I was a little confused with what was being requested, so I updated the descriptions with some examples.
=> Improve descriptions a little bit with examples.

examples/examples-release-13/src/main/java/io/kubernetes/client/examples/InformerExample.java, examples/examples-release-14/src/main/java/io/kubernetes/client/examples/InformerExample.java, examples/examples-release-15/src/main/java/io/kubernetes/client/examples/InformerExample.java, util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Fixes: https://github.com/kubernetes-client/java/issues/2102
=> Deprecating no-arg informer-factory

examples/examples-release-15/src/main/java/io/kubernetes/client/examples/DeployRolloutRestartExample.java
This is a client-java v15.x compatible example of a Deployment resource rollout restart function which involves several indirect/non-trivial steps, which I thought could be quite useful for anyone seeking to have greater programmatic control over their Kubernetes deployments.
=> Add Deployment rollout restart example

util/src/test/java/io/kubernetes/client/ExecTest.java
=> Deflake ExecTest

extended/src/test/java/io/kubernetes/client/extended/controller/DefaultControllerTest.java
=> Deflake the DefaultControllerTest.

extended/src/test/java/io/kubernetes/client/extended/controller/DefaultControllerTest.java, extended/src/test/java/io/kubernetes/client/extended/controller/LeaderElectingControllerTest.java
=> Deflake another test

util/src/main/java/io/kubernetes/client/informer/SharedInformer.java, util/src/main/java/io/kubernetes/client/informer/TransformFunc.java, util/src/main/java/io/kubernetes/client/informer/exception/ObjectTransformException.java, util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java, util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerWireMockTest.java
=> Add support for transforming objects in shared informers

pom.xml
Related to issue #2154, cherry pick of [#2061](https://github.com/kubernetes-client/java/pull/2061),
Also updated caffeine version, to solve conflict,
Let me know if I'm missing anything
=> Bump protobuf-java from 3.19.1 to 3.19.2 for release 14

.github/workflows/maven.yml, extended/src/test/java/io/kubernetes/client/extended/controller/DefaultControllerTest.java, extended/src/test/java/io/kubernetes/client/extended/controller/LeaderElectingControllerTest.java, extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectionTest.java
=> Add macos to the matrix build.

kubernetes/src/main/java/io/kubernetes/client/openapi/JSON.java
Signed-off-by: Raymond Augé <raymond.auge@liferay.com>
=> don't use internal gson package when JDK provides alternative

.github/workflows/generate.yml, .gitignore, fluent-gen/README.md, fluent-gen/generate.sh
@brendandburns this automated workflow can help us to do the code generation via manually running workflow, in the end,a PR will be opened. see an example at https://github.com/yue9944882/java/pull/23/files
=> Adding a gh-action for generated java job

.github/workflows/generate.yml, .gitignore, fluent-gen/README.md, fluent-gen/generate.sh
=> Cherrypick  #2197 to release-15

.github/workflows/codeql-analysis.yml, .github/workflows/generate.yml, .github/workflows/snapshot.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
=> Set permissions for GitHub actions

extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultRateLimitQueueTest.java
Fixes flakiness in https://github.com/kubernetes-client/java/runs/6603599991?check_suite_focus=true
=> Flake: Fixes rate-limit queue flakiness

.github/workflows/generate-crd.yml, docs/generate-model-from-third-party-resources.md
this pull adds a new github action workflow for generating java models easily w/o preparing local environment
=> CRD generate gh-action workflow

extended/src/test/java/io/kubernetes/client/extended/controller/LeaderElectingControllerTest.java
by debugging into the flakiness in https://github.com/kubernetes-client/java/pull/2270, i believe this pull will solve the flakiness in leader-election test permernantly
=> Fixes flakiness testLeaderElectionController

util/src/main/java/io/kubernetes/client/util/authenticators/GCPAuthenticator.java
Hi, currently GCPAuthenticator support for environment without `gcloud` is broken. The code will throw `NullPointerException` when being executed:
```
Exception in thread "main" java.lang.NullPointerException
at io.kubernetes.client.util.authenticators.GCPAuthenticator.refresh(GCPAuthenticator.java:103)
at io.kubernetes.client.util.KubeConfig.getCredentials(KubeConfig.java:220)
at io.kubernetes.client.util.credentials.KubeconfigAuthentication.<init>(KubeconfigAuthentication.java:59)
at io.kubernetes.client.util.ClientBuilder.kubeconfig(ClientBuilder.java:299)
```
```
// Where exception is thrown
// File: util/src/main/java/io/kubernetes/client/util/authenticators/GCPAuthenticator.java
101:  if (this.gc == null) this.gc = GoogleCredentials.getApplicationDefault().createScoped(scopes);
102: …
```
=> Fix: GCPAuthenticator throws null exception in some cases

util/src/main/java/io/kubernetes/client/PodLogs.java, util/src/test/java/io/kubernetes/client/PodLogsTest.java
=> Close ResponseBody in PodLogs on error

extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
Expand the javadocs for the main entry point to the LeaderElector,
trying to make explicit some of the assumptions that users should take
into account regarding the re-acquisition of leadership status.
Signed-off-by: Galo Navarro <anglorvaroa@gmail.com>
=> leader elector: improve javadocs

util/src/main/java/io/kubernetes/client/util/taints/Taints.java, util/src/test/java/io/kubernetes/client/util/taints/TaintsTest.java
- fixed spelling mistake in NO_EXECUTE toString Method.
- added unit tests for NO_EXECUTE toString Method
Fixes #2340
=> fix for NO_EXECUTE toString Method

pom.xml
Upgraded OkHttp From 4.9.2 To 4.10.0,
as part of [#2358](https://github.com/kubernetes-client/java/issues/2358)
Related to [#2360](https://github.com/kubernetes-client/java/pull/2360) after fixing the CNCF CLA problem.
=> Bump OkHttp From 4.9.2 To 4.10.0

extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlExec.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPortForward.java, util/src/main/java/io/kubernetes/client/Exec.java, util/src/test/java/io/kubernetes/client/ExecTest.java
Signed-off-by: Daniel Arteaga Barba <darteaga@vmware.com>
This PR will try to implement an acceptable approach for the following proposal #2361
See an example of use.
```java
@Override
public Process exec(String[] args, boolean stdin, boolean tty) {
try {
Exec kubeExec = new Exec(client);
kubeExec.setOnUnhandledError(this::logUnhandledExceptions);
return kubeExec.exec(namespace, host, args, null, stdin, tty);
} catch (ApiException | IOException e) {
throw Errors.internal("Error executing command on the remote host", e).get();
}
}
private void logUnhandledExceptions(final Throwable throwable) {
log.debug(throwable.getMessage(), throwable);
}
```
=> Add a consumer for unhandled errors to Exec.java

util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
Signed-off-by: Daniel Arteaga Barba <darteaga@vmware.com>
This PR is a proposal for the following issue:https://github.com/kubernetes-client/java/issues/2309 based in this comment: https://github.com/kubernetes-client/java/issues/2309#issuecomment-1255038176
=> fix: WebSocketOutputStream wait to write until WebSocket queue is released

extended/src/main/java/io/kubernetes/client/extended/workqueue/DefaultDelayingQueue.java, extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultDelayingQueueTest.java
The previous code uses `Instant.now()` which is subject to time changes from NTP or `adjtime(...)`
By switching to `nanoTime` which is only used for measuring duration we eliminate these potential issues.
This _may_ be why #2396 is still happening.
Note that this bug is still present in the upstream `client-go` I will send a fix there also.
=> Fix the default delay queue to use a fixed time source.

util/src/main/java/io/kubernetes/client/util/SSLUtils.java, util/src/test/java/io/kubernetes/client/util/SSLUtilsTest.java
This pull request implements private key loading refactoring proposed in #2440.
The implementation refactors the `SSLUtils.loadKey` method to use the Bouncy Castle `PEMParser` for all types of private keys. The existing implementation uses `PEMParser` for `ECDSA` Private Keys, and the proposed changes eliminate the need for custom DER and PKCS8 parsing. Changes include updates to the SSLUtils test class, providing a reusable test method and also asserting expected algorithm values for parsed Private Keys.
=> Refactor SSLUtils.loadKey using PEMParser

extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlLabelTest.java
This fixes tests that weren't really testing much previously.
=> Add validation that the request body is as expected in kubectl label.

pom.xml
Picking https://github.com/kubernetes-client/java/pull/2362 to release-15 branch
=> Cherrypick(release-15): Bump OkHttp From 4.9.2 To 4.10.0 

pom.xml
Picking https://github.com/kubernetes-client/java/pull/2362 tot release-16
=> Cherrypick(release-16): Bump okhttp from 4.9.2 to 4.10.0

pom.xml
Picking https://github.com/kubernetes-client/java/pull/2474 to release-16
=> Cherrypick(release-16): Bump protobuf-java from 3.21.2 to 3.21.8

.github/workflows/release.yml
=> Switch to Java 17 for release action.

pom.xml, util/src/main/java/io/kubernetes/client/util/FilePersister.java, util/src/main/java/io/kubernetes/client/util/generic/dynamic/Dynamics.java
=> [chore] switch to non-default constructor for YAML and add a lint rule.

extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlAnnotateTest.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlApplyTest.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlCreateTest.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlLabelTest.java, util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java, util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiForCoreApiTest.java, util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java, util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesGetApiTest.java, util/src/test/java/io/kubernetes/client/util/generic/KubernetesApiResponseTest.java
This change updates GenericKuberentesApi to have asynchronous methods similar to each of the existing synchronous methods. I've chosen to have the callback be an implementation of Consumer<KubernetesApiResonse<ApiType>> and have each method return Future<KubernetesApiResponse<ApiType>> to continue the pattern of not exposing symbols from OkHttp.
Second, and much more minor, I was having a lot of trouble building locally because of "port already in use" messages from WireMock. I saw that the wireMockConfig().dynamicPort() pattern was already in use elsewhere in the code base so I've updated more test classes.
=> Add asynchronous methods to GenericKubernetesApi

util/src/main/java/io/kubernetes/client/util/generic/dynamic/DynamicKubernetesTypeAdaptorFactory.java, util/src/test/java/io/kubernetes/client/util/generic/dynamic/DynamicKubernetesTypeAdaptorFactoryTest.java
When a `TypeAdapterFactory` does not handle the type in its `create` method, the protocol is for it to return `null`. Calling `gson.getDelegateAdapter` is only appropriate for factories that wrap the results of other factories.
See https://github.com/google/gson/issues/2312.
=> Fix `DynamicKubernetesTypeAdaptorFactory` when it does not apply.

util/src/main/java/io/kubernetes/client/util/WebSockets.java
We are trying to use the `PortForward` class to communicate with our kubernetes pods for testing purposes. We've been having trouble with tunneled connections timing out or receiving unexpected EOFs. There is little documentation about how this api server proxy works, which makes diagnosing any problems a struggle.
I added voluminous debug logs and discovered that the server seems to be sending an `onClosing` event with a code of 1000, indicating that it will not communicate with us further in this session.
I don't understand why the api server proxy is closing our session which we intend to use further. But, if it does, it does no good to keep it open clientside: you will wait as long as you like but the server won't send any more data.
Shutting down the client side in this case seems to …
=> WebSockets: handle onClosing

util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java
Use synchronization classes instead of Thread.sleep in test cases
PR is to fix one of the issue under this PR umbrella #1223
=> Use synchronization classes instead of Thread.sleep in test cases

.github/workflows/maven.yml
Spotless has moved to only support JDK 11+, see #2579
=> Update spotless testing to use JDK 11

util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerWireMockTest.java
This PR removes thread.sleep and uses synchronization classes similar to fix made for issues under umbrella #1223 
This should also fix flaky test mentioned in #2436
=> Use synchronization classes instead of Thread.sleep and fix flaky test

.github/workflows/maven.yml
elgohr/Publish-Docker-Github-Action@master is not supported anymore
=> Updated elgohr/Publish-Docker-Github-Action to a supported version (v5)

extended/pom.xml, pom.xml
Reverts kubernetes-client/java#2618
the new build 0.8.9 of jacoco was reverted from maven central, which leaving the test pipelines in this repo constantly failing. downgrading the version to fix it.
=> Revert "build(deps): bump jacoco-maven-plugin from 0.8.8 to 0.8.9"

extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlLabelTest.java
Updated KubectlLabel class to fix bug #2638 where the label was not deleted properly. The deleteLabel() method now removes the label key from the addingLabels map, and the resulting JSON object in the PUT request correctly omits the label key instead of setting it to null. Also updated the corresponding unit test to reflect the changes.
=> Fixed bug: label being set as null instead of deleted

client-java-contrib/Dockerfile
This commit updates the Dockerfile in the client-java-contrib directory. It modifies the installation of kubectl to use the updated URL: https://dl.k8s.io/release/v1.20.2/bin/linux/amd64/kubectl.
The previous URL (https://storage.googleapis.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubectl) is no longer valid.
/kind cleanup
/kind deprecation
There are still references to https://storage.googleapis.com/kubernetes-release instead of https://dl.k8s.io/
dl.k8s.io is the correct advertised download host and will eventually move to be fastly shielding a fully community-owned bucket
ref: https://github.com/kubernetes/k8s.io/issues/2396
=> use dl.k8s.io, not kubernetes-release bucket

.github/workflows/maven.yml, CONTRIBUTING.md, examples/examples-release-14/README.md, examples/examples-release-15/README.md, fluent-gen/pom.xml, kubernetes/pom.xml, pom.xml
- Fix Maven build warnings
- Invalid use of `prerequisites` tag (replaced by `maven-enforcer-plugin`)
- Missing version for `jacoco-maven-plugin` (introduced by https://github.com/kubernetes-client/java/pull/2493)
- Fix minor doc issues (typos and broken link)
=> Fix Maven build warnings and minor doc issues

util/src/main/java/io/kubernetes/client/informer/cache/Controller.java
Cherry pick of #2693 on version 18.0.0
#2693: Shutdown resync and reflect executors now in
=> cherry pick of #2693: Shutdown resync and reflect executors now in

util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java, util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java
The PR is based on [Issue 2733](https://github.com/kubernetes-client/java/issues/2733)
Observe the problem description there.
=> fix: NPE in GenericKubernetesApi if response body is empty

extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlApiResources.java, util/src/main/java/io/kubernetes/client/Discovery.java, util/src/main/java/io/kubernetes/client/util/ModelMapper.java, util/src/main/java/io/kubernetes/client/util/exception/IncompleteDiscoveryException.java, util/src/test/java/io/kubernetes/client/DiscoveryTest.java
fix #2719
Exceptions raised when calling an API to obtain all the resources it manages are now ignored. So when an API is unavailable, discovery doesn't stop, and all others APIs are processed.
This PR means that when ModelMapper calls Discovery#findAll and at least one api is unavailable, all metadata related to resources managed by unavailable APIs will not be updated in ModelMapper until the next refresh (30 minutes by default).
In addition, this PR allows the KubectlApiResources class (the extended client equivalent of `kubectl api-resources`) to list all resources managed by available API .
=> fix: discovery fail when at least one api is unavailable

pom.xml
We're seeing OWASP scan reports about okio, which is included by okhttp3. I'm curious about why Dependabot didn't update this dependency? Whatever the answer, here are all of the missing updates except for those from Spring, which seem to require other, compensating changes.
=> Update dependencies except for Spring

extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultRateLimitQueueTest.java
Fixing the following flaky tests by relaxing timestamp precision (from nano to milli)
```
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
Error:  Failures: 
Error:    DefaultRateLimitQueueTest.testSimpleRateLimitQueue:57 Unexpected time: 499985735 vs 500000000
Error:  Tests run: 102, Failures: 1, Errors: 0, Skipped: 0
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project client-java-extended: There are test failures.
Error:  
Error:  Please refer to /home/runner/work/java/java/extended/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  -> [Help 1]
Error:  
Error:  To see the full …
```
=> Fixing flaky rate-limiting test

client-java-contrib/admissionreview/pom.xml, examples/examples-release-16/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/pom.xml
This should skip staging these jars to nexus
https://help.sonatype.com/repomanager3/integrations/nexus-repository-maven-plugin#NexusRepositoryMavenPlugin-Configuration
And hopefully fix the release break here:
https://github.com/kubernetes-client/java/actions/runs/6226166183/job/16898118043
=> Update pom.xml to skip release (I hope)

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-16/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/pom.xml, extended/pom.xml, fluent-gen/pom.xml, fluent/pom.xml, kubernetes/pom.xml, kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
Bumping root version to 20.0.0-SNAPSHOT as we cut a `release-19` branch
after this we can regenerate using 1.28 k8s openapi spec
=> Bump staging version to 20.0.0-SNAPSHOT

examples/examples-release-19/pom.xml, examples/examples-release-19/src/main/java/io/kubernetes/client/examples/EKSAuthenticationExample.java, pom.xml, util/pom.xml, util/src/main/java/io/kubernetes/client/persister/ConfigPersister.java, util/src/main/java/io/kubernetes/client/persister/FilePersister.java, util/src/main/java/io/kubernetes/client/util/ClientBuilder.java, util/src/main/java/io/kubernetes/client/util/KubeConfig.java, util/src/main/java/io/kubernetes/client/util/credentials/EKSAuthentication.java, util/src/main/java/io/kubernetes/client/util/eks/AWS4STSSigner.java, util/src/main/java/io/kubernetes/client/util/eks/AWS4SignerBase.java, util/src/main/java/io/kubernetes/client/util/eks/BinaryUtils.java, util/src/main/java/io/kubernetes/client/util/eks/HttpUtils.java, util/src/test/java/io/kubernetes/client/util/FilePersisterTest.java, util/src/test/java/io/kubernetes/client/util/credentials/EKSAuthenticationTest.java
This authentication class helps connecting to an EKS cluster w/o requiring having "aws" cli in the $PATH. Before this CR, users can still talk to EKS cluster by using the exec plugin, but now the new `EKSAuthentication` class will help them get rid of that CLI  dependency. EKS cluster uses a bearer token which is signed by AWS AK/SK using [SIGv4](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html) in a customized format.
(I think this is the first implementation of EKS bearer token generator in Java, the authentication protocol is never documented anywhere :/)
=> EKS authentication based on AWS Sigv4

kubernetes/.openapi-generator-ignore
=> Remove JSON.java from openapi ignore file.

kubernetes/src/test/java/io/kubernetes/client/openapi/JSONTest.java
```
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 s -- in io.kubernetes.client.custom.IntOrStringTest
[INFO] Running io.kubernetes.client.custom.QuantityFormatterTest
[INFO] Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 s -- in io.kubernetes.client.custom.QuantityFormatterTest
[INFO] Running io.kubernetes.client.custom.SuffixFormatterTest
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.010 s -- in io.kubernetes.client.custom.SuffixFormatterTest
[INFO] Running io.kubernetes.client.gson.V1StatusJsonDeserializerTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.103 s -- in io.kubernetes.client.gson.V1StatusJsonDeserializerTest
[INFO] Running io.kubernetes.client.openapi.JSONTest …
```
=> Ignore json test temporarily for code generation

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-16/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/pom.xml, extended/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
Reverts kubernetes-client/java#2828
@brendandburns looks like 19.0.0 is successfully out, am i missing anything? if that worked, we should revert this PR so the version matches
=> Revert "Release-19: Reset release 19 pom version to 19.0.0-SNAPSHOT"

kubernetes/src/test/java/io/kubernetes/client/openapi/JSONTest.java
> https://github.com/kubernetes-client/java/actions/runs/6631723154/job/18015844874
> Error:  io.kubernetes.client.openapi.JSONTest.testSerializeByteArray -- Time elapsed: 0.420 s <<< FAILURE!
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
the code generation failed again, need to suppress another unit test around JSON class to get it work
=> Suppress JSON unit test for code generation

kubernetes/src/test/java/io/kubernetes/client/openapi/JSONTest.java
> https://github.com/kubernetes-client/java/actions/runs/6647839995/job/18063931671
It fails one test at a time.. Ignoring all JSON test to unblock the code gen
=> Ignore all JSON test for next code gen

util/src/main/java/io/kubernetes/client/Attach.java
In #900, the streams for resizing and connection errors were added for Exec. This PR adds the same streams for Attach.
This makes it possible to resize the terminal when using Attach by getting the stream from the AttachResult.
=> Expose resize & connection-error streams for Attach

spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerCreatorTest.java
**Describe the bug**
The order dependent flakiness was detected when `KubernetesReconcilerCreatorTest.java` was run before the `KubernetesInformerCreatorTest.java`. The error appeared at line 157 in `KubernetesInformerCreatorTest.java`. It was suppose to get 1 result the calling `getRequestedFor()`for specific `urlPattern`, however, the actual result was 2.
**Fix log**
The reason that the flakiness showed up was due to the object `SharedInformerFactory`. Since in the `KubernetesReconcilerCreatorTest.java`, we called `startAllRegisteredInformers` in the test and registered the `V1Pod`, but did not call `stopAllRegisteredInformers` to stop the registration, and then when next test class was run, there were already something in the database. Eventually, that lead to the unexpected output 2 …
=> Fix order-dependent flakiness in KubernetesReconcilerCreatorTest.java

extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDelete.java
This PR fixes #2876, an issue where attempting to delete a resource that doesn't exist throws an exception and causes the user to catch the exception.
Now, by setting the ignoreNotFound flag, exceptions don't have to be explicitly caught.
=> Add ignoreNotFound flag to KubectlDelete.java

kubernetes/src/main/java/io/kubernetes/client/custom/QuantityFormatter.java, kubernetes/src/test/java/io/kubernetes/client/custom/QuantityFormatterTest.java
This issue is caused by the `unscaledValue()` method of BigDecimal returning a BigInteger, which is then forcibly cast to a long, potentially causing overflow. 
If the value of `quantity.getNumber()` is greater than `Long.MAX_VALUE`, then overflow will occur.
=> Fixed overflow issue when handling large inputs in QuantityFormatter

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-16/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/pom.xml, extended/pom.xml, fluent-gen/pom.xml, fluent/pom.xml, kubernetes/pom.xml, kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
@brendandburns alternatively, do you think we should make these legacy java8-compatible codes a new module (specifically a new module name) or the same module name with a suffixed version e.g. `19.0.0.legacy`?
=> Branch(java8): Add `-legacy` version qualifier to java8 compatible modules

.github/workflows/maven.yml
@brendandburns i think merging this into master branch should apply to all incoming PRs globally, if it doesn't work i will cherrypick this PR to `master-java8` branch in a follow-up
=> Chore: Run github action for PR against `master-java8` branch

util/src/main/java/io/kubernetes/client/util/ModelMapper.java
When running in IDE or a thin jar, it is ok.
When running with a fat jar in server, new JarFile can not open and read the entries.
=> #2241 fix bug: when running with a fat jar, need to read entries with openConnection

.github/workflows/generate.yml, .github/workflows/maven.yml
This PR (1) pins openapi generator version to v4.3.1 for `master-java8` branch so it will constantly skip java8 non-compatible upgrades (2) enables github action CI so the java8 source code can have test/CI coverage
=> Branch(master-java8): Pin generator version to v4.3.1

.github/workflows/generate.yml, kubernetes/.openapi-generator-ignore, scripts/patches/json.diff, scripts/patches/list-meta.diff, scripts/patches/status.diff
since we bumped the openapi generator to v6 from v4, there're a few additional manual code changes we need to made on top of the generated code. in the past, the only manual edits are in the `JSON` class however now it's extended to `V1ListMeta` and `V1Status` to be compatible with kubernetes graceful deletion (the returned type for k8s delete API is a status object however it will return the deleted object upon graceful/progressive deletion). this pull automates those manual changes by git patches instead of ignoring these models generation by the `.openapi-generator-ignore` configuration file. 
with this PR, the code generation workflow behavior will change from (1) ignoring manually editted source files to (2) always re-generate but apply git patches after generation.
an example of the …
=> Tracking manual edits in git diffs to unlock openapi ignore

.github/workflows/generate.yml, .github/workflows/release.yml
those PR made by the workflows in this repo doesn't pass CLA validation somehow anymore, updating the git commit author info to another kubernetes robot to bypass the check:
https://github.com/kubernetes-client/java/pull/3042
=> Update git generated commit author to pass CLA

RELEASES.md
for the future releases, we need to start by creating two new release branch e.g.:
- release-20 (checkout from `master`)
- release-legacy-20 (checkout from `master-java8`)
and the maven artifact version format will be:
- X.Y.Z (with or without -SNAPSHOT suffix)
- X.Y.Z-legacy (with or without -SNAPSHOT suffix)
=> Doc: Update release doc for clarifying legacy branch workflow

util/src/main/java/io/kubernetes/client/Exec.java, util/src/test/java/io/kubernetes/client/ExecTest.java
The class `Exec.ExecutionBuilder` has three `private final` properties: `namespace`, `name`, and `command`. While it makes little sense to provide `null` as their values, if this happens, this would throw a `NullPointerException` at a much later time, complicating the debugging process.
This commit implements a fail-fast `null` guards for these variables.
Example:
```java
import io.kubernetes.client.Exec;
public class Test {
public static void main(String args[]) throws Exception {
Exec exec = new Exec(null);
Exec.ExecutionBuilder builder = exec.newExecutionBuilder("", "", null);
builder.execute();
}
}
```
```console
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "io.kubernetes.client.openapi.ApiClient.escapeString(String)" because "this.localVarApiClient" is …
```
=> Add null guards for Exec.ExecutionBuilder

util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java, util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerTest.java
While internally, controllers use `Threads.threadFactory`, `DefaultSharedIndexInformer` starts an ad-hoc thread. This makes it invisible to instrumentation setup via `Threads.setDefaultThreadFactory`. This changes the constructor to also use the same.
I noticed this trying to instrument spring-cloud-kubernetes, and was wondering why I didn't see this thread.
=> Change DefaultSharedIndexInformer constructor to use threadFactory

examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/examples-release-20/pom.xml, examples/examples-release-latest/pom.xml, extended/pom.xml, pom.xml, spring/pom.xml, util/pom.xml
wiremock contains lower version of jackson. new version wiremock can only work with new jackson (2.16.1)
=> update: update wiremock & jackson

client-java-contrib/admissionreview/pom.xml, e2e/pom.xml, fluent-gen/pom.xml, fluent/pom.xml, kubernetes/pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
the group ID is inherited from the parent, and causes an IDE warning in IntelliJ
=> build: remove redundant groupId in poms that do it

examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/examples-release-20/pom.xml, examples/examples-release-latest/pom.xml, extended/pom.xml, kubernetes/pom.xml, kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java, kubernetes/src/main/java/io/kubernetes/client/custom/IntOrStringJacksonSerializer.java, kubernetes/src/test/java/io/kubernetes/client/custom/IntOrStringTest.java, pom.xml, spring/pom.xml, util/pom.xml
It's OK when using Gson, but not all of the project want to dependency Gson when jackson is the default serialize tool.
Serialization tool would serialize any field with getter even if you don't want to serialize it.. When we serialize an object witch contant IntOrString, we got the exception.
Here is an adapter with Gson, but not for Jackson, Jackson is the default serialization tool in spring framework. So we got the issues like: https://github.com/kubernetes-client/java/issues/2593, https://github.com/kubernetes-client/java/issues/2566, (34 issues).
So it added a JacksonSerializer for Jackson.
This PR depends on another PR #3126
=> fix: Add JacksonSerializer to serialize IntOrString

examples/examples-release-17/src/main/java/io/kubernetes/client/examples/ExpandedExample.java, examples/examples-release-18/src/main/java/io/kubernetes/client/examples/ExpandedExample.java, examples/examples-release-19/src/main/java/io/kubernetes/client/examples/ExpandedExample.java, examples/examples-release-20/src/main/java/io/kubernetes/client/examples/ExpandedExample.java, examples/examples-release-latest/src/main/java/io/kubernetes/client/examples/ExpandedExample.java, extended/src/main/java/io/kubernetes/client/extended/controller/ControllerManager.java, spring-aot/src/main/java/io/kubernetes/client/spring/aot/KubernetesBeanFactoryInitializationAotProcessor.java, spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java, util/src/main/java/io/kubernetes/client/Copy.java, util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java, util/src/main/java/io/kubernetes/client/util/ClientBuilder.java, util/src/main/java/io/kubernetes/client/util/KubeConfig.java, util/src/main/java/io/kubernetes/client/util/ModelMapper.java, util/src/main/java/io/kubernetes/client/util/Yaml.java, util/src/main/java/io/kubernetes/client/util/eks/HttpUtils.java
This fixes some practice not all of which easy to notice manually, notably use SLF4J parameters instead of string concatenation.
```bash
./mvnw -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-logging-frameworks:RELEASE -Drewrite.activeRecipes=org.openrewrite.java.logging.slf4j.Slf4jBestPractices
```
=> openrewrite: apply Slf4jBestPractices

pom.xml
This is a part of me trying to get us to the point we can build with JDK 21
Before, we have this error and now we don't
```bash
$ ./mvnw spotless:apply
--snip--
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.43.0:apply (default-cli) on project client-java-parent: Execution default-cli of goal com.diffplug.spotless:spotless-maven-plugin:2.43.0:apply failed: You are running Spotless on JVM 21. This requires google-java-format of at least 1.17.0 (you are using 1.15.0).
```
=> Update google-java-format to LTS 17

pom.xml
adal4j is an optional dependency. This means that for a project to use it, they must declare their own dependency. As such, it doesn't always show up in CVE reports as we do not require this dependency.
However, some will detect it and I also notice IntelliJ will. After updating its indirect dep, IntelliJ's detector is no longer aware of any CVE related to this. 
Hopefully, this buys time, and removes any short term action about adal4j except deleting the code that uses it.
See #3169
=> Resolve indirect dep CVE from adal4j

pom.xml
Bumps org.apache.commons:commons-compress from 1.25.0 to 1.26.0.
---
updated-dependencies:
- dependency-name: org.apache.commons:commons-compress dependency-type: direct:production update-type: version-update:semver-minor ...
=> build(deps): bump org.apache.commons:commons-compress

spring-aot/pom.xml
We accidentally masked the parent definition of spring-boot version and in doing so pin older dependencies than we meant to. This was detected by `trivy repo .`.
=> Fix CVEs brought in by accidental spring boot version override

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Commit 544f434a94a1412b9f2f2df29cfac3e6c8208a93 upgraded Spring to version 6.0.11.
According to https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions , Spring >= 6 requires Java 17.
The devcontainer is still using Java 11, which causes errors when compiling the project in a devcontainer.
This PR sets the Java version in the devcontainer to 17, after which the project compiles without errors.
=> Update devcontainer to use Java 17 (required for Spring >= 6)

.github/workflows/maven.yml
MacOS + GitHub Actions no longer supports Java8
=> Update maven.yml for legacy branch

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-latest/pom.xml, examples/pom.xml, extended/pom.xml, fluent-gen/pom.xml, fluent/pom.xml, kubernetes/pom.xml, kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java, kubernetes/src/main/java/io/kubernetes/client/openapi/Configuration.java, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
To prepare for cutting 1.30 release, bumping root pom version from 20.0.0 to 21.0.0.
Next step: will cut a new release branch `release-21` and then run the release job.
=> Bump root pom to 21.0.0-SNAPSHOT

kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java, kubernetes/src/test/java/io/kubernetes/client/custom/QuantityTest.java
- overrode `hashCode` in `Quantity`
- added test which compares two sets of equal elements
It `closes` #3490
=> Override hashCode in Quantity

util/src/main/java/io/kubernetes/client/informer/cache/Cache.java
**Fix to the issue**:  #3510 
Memory leak in Cache indices when item is deleted #3510
=> Fixed memory leak in cache indices when item is deleted

extended/pom.xml, pom.xml
The groupId `com.github.vladimir-bukhtoyarov` has migrated to `com.bucket4j` see https://mvnrepository.com/artifact/com.github.vladimir-bukhtoyarov/bucket4j-core/8.0.1
Note:
I have not upgraded the version (there are newer versions). This is to allow this to be a like-for-like replacement.
Once this migration is made, dependabot will be able to see the newer versions and propose future upgrades.
=> Update pom.xml - com.bucket4j migration

extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventSpamFilter.java, extended/src/main/java/io/kubernetes/client/extended/workqueue/ratelimiter/BucketRateLimiter.java, pom.xml
Migrate `@deprecated` `Bucket4J` class usage to `Bucket` class to unblock dependabot upgrade of bucket4j from `8.0.1` to `8.10.1`. 
I include the upgrade of the Bucket4J library as proposed by dependabot to demonstrate that it all works together.
Tested locally.
=> Migrate deprecated Bucket4J class usage to Bucket class to unblock upgrade

extended/pom.xml, pom.xml, spring/pom.xml, util/pom.xml
This PR moves `optional` tags to module POMs since they are not inherited in `dependencyManagement`. See https://github.com/kubernetes-client/java/issues/3533 for more details.
Resolves https://github.com/kubernetes-client/java/issues/3533.
=> Move `optional` tags to module POMs

extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDelete.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlDeleteTest.java, util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
closes: #3463 
Added an option to pass deleteOptions in kubectlDelete.
=> Added support for passing delete options when using kubectlDelete.#3463

extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDrain.java
Porting changes from PR https://github.com/kubernetes-client/java/pull/3537 for CLA issue
=> fix: correct work of DaemonSetIgnore #3545

extended/pom.xml, extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventSpamFilter.java, extended/src/main/java/io/kubernetes/client/extended/workqueue/ratelimiter/BucketRateLimiter.java, pom.xml
Migrate deprecated Bucket4J class usage to Bucket class to unblock upgrades
=> Migrate deprecated Bucket4J class usage to Bucket class to unblock upgrades

util/src/main/java/io/kubernetes/client/util/SSLUtils.java
Prefer FIPS version of bouncy castle if available. Otherwise, fallback to non FIPS version.
=> feat: add support for FIPS bouncy castle #3590

util/src/main/java/io/kubernetes/client/util/ClientBuilder.java, util/src/main/java/io/kubernetes/client/util/credentials/KubeconfigAuthentication.java, util/src/main/java/io/kubernetes/client/util/credentials/RefreshAuthentication.java, util/src/test/java/io/kubernetes/client/util/credentials/KubeconfigAuthenticationTest.java, util/src/test/java/io/kubernetes/client/util/credentials/RefreshAuthenticationTest.java
This is a replacement for https://github.com/kubernetes-client/java/pull/3406 which had some design flaws due to the complicated way that auth is implemented w/ the code generator.
This follows the same pattern as was previously there for file tokens.
This is a little hacky and should be fixed in the upstream generator, but it works for now at least for tokens.
TODO: figure out if we can do something similar for certificates.
=> Add token refresh for exec credentials.

extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlDeleteTest.java
This pull requests removes the incorrect API path in the KubectlDelete unit tests:
> /apis/batch%2Fv1/batch%2Fv1/namespaces/foo/jobs/bar
to 
> /apis/batch/v1/namespaces/foo/jobs/bar
=> Nit: Sanitize mock API paths in the tests

client-java-contrib/publish-gen-image.sh, scripts/publish-crd-model-gen-image.sh
This change makes it convenient to publish a copy of crd-model-gen to a private container registry.
Refactor client-java-contrib/publish-gen-image.sh to accept parameters via environment variables. At the same time, refactor scripts/publish-crd-model-gen-image.sh to remove duplicated logic. This also serves as an example of how to invoke publish-gen-image.sh.
In case there are existing workflows that depend on these two scripts, I have not renamed either of them, and they have the same behavior when no environment variables are provided.
=> Add params to publish-gen-image.sh

pom.xml
Bump protobuf to [4.27.5](https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java/4.27.5) to remediate CVE-2024-7254
=> Bump protobuf to remediate CVE-2024-7254

extended/src/main/java/io/kubernetes/client/extended/controller/builder/DefaultControllerBuilder.java
When overriding the workQueue for the controller, the original queue must be shut down to avoid thread leakage. If the original queue is not shut down here, it will remain active even after the controller is shut down. This is because the controller's queue has been replaced by the newly created queue.
Related Issue: https://github.com/kubernetes-client/java/issues/3738
=> Shutdown original queue before override

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/examples-release-20/pom.xml, examples/examples-release-latest/pom.xml, examples/pom.xml, extended/pom.xml, fluent-gen/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
=> Since PR generation is still not working, manual clone of the 22.0.0 release changes

util/src/main/java/io/kubernetes/client/Exec.java, util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java, util/src/test/java/io/kubernetes/client/ExecTest.java
Reimplements #3657 since that PR has gone idle.
=> Add support for terminal resize in ExecProcess

util/src/main/java/io/kubernetes/client/util/ModelMapper.java
Cherry pick #2952 to Release-19 branch
=> Cherry Pick #2952 To Release 19

util/src/main/java/io/kubernetes/client/util/credentials/RefreshAuthentication.java, util/src/main/java/io/kubernetes/client/util/credentials/TokenFileAuthentication.java, util/src/main/java/io/kubernetes/client/util/exception/TokenAquisitionException.java, util/src/test/java/io/kubernetes/client/util/credentials/TokenFileAuthenticationTest.java
This pull request addresses the TODO comment:
> // TODO: Merge this with TokenFileAuthentication.
It simplifies the TokenFileAuthentication by taking RefreshAuthentication as the parent class
=> Refactor: Merge TokenFile auth with refresh auth

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-16/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/pom.xml, extended/pom.xml, fluent-gen/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
> https://github.com/kubernetes-client/java/actions/runs/12817765842/job/35741724724
We cannot publish a `21.0.2` version due to the pom version on the release branch is falling behind.. This PR will unblock the workflow
=> Manually bumping release-legacy-21 pom version to 21.0.2-legacy-SNAPSHOT

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-16/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/pom.xml, extended/pom.xml, fluent-gen/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
This PR is a manual release code sync after publishing `21.0.2-legacy` which contains the following two commits:
1. Bump the version to 21.0.2-legacy, which is where we're going to tag and push `21.0.2-legacy` in this repo.
2. Bump the version to 21.0.3-legacy-SNAPSHOT for preparing the next release.
/cc @brendandburns
=> Manual update release 21.0.2-legacy

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-latest/pom.xml, examples/pom.xml, extended/pom.xml, fluent-gen/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
Previously we have cut a `22.0.0` release from `release-22` branch, however the pom version was expected to be bumped to `22.0.1-SNAPSHOT` after the release. It should be automatically done via the release plugin but due to the workflow permission we lost the commit. This PR syncs the commit on the release branch.
=> Release-22: Bump the latest pom version to 22.0.1-SNAPSHOT

util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java, util/src/test/java/io/kubernetes/client/informer/SharedInformerFactoryTest.java
The aim is to facilitate the reuse of existing cached informers when creating informers through SharedInformerFactory.
Currently, SharedInformerFactory caches only the first informer created for each API type. Developers who wish to avoid creating a new informer each time must first call SharedInformerFactory#getExistingSharedIndexInformer before proceeding with creation.
By setting reuseExistingCachedInformer to true, SharedInformerFactory will automatically reuse existing cached informers instead of creating new ones. This approach simplifies the process and clearly indicates whether to utilize the cached factory, thereby reducing potential confusion.
The discussion can be found here [Issue](https://github.com/kubernetes-client/java/issues/3849)
=> Enable the reuse of cached informers on creation by `SharedInformerFactory`.

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-16/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/pom.xml, extended/pom.xml, fluent-gen/pom.xml, fluent/pom.xml, kubernetes/pom.xml, kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
This PR bumps the root pom version on master-java8 which is the master branch for legacy support to 22.0.0-*.
As follow-up, I will cut another release branch for 22.0.x-legacy, probably named `release-legacy-22-fix` as the current content on `release-legacy-22` branch is not correct
=> Bump master java8 22.0.0-legacy

kubernetes/.openapi-generator-ignore
So that it can be re-generated/refreshed by openapi model generation workflow
=> Branch(master-java8): Remove "JSON.java" from openapi gen ignore file

util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java, util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesListApiTest.java
Hi, there
This pr fixes missing continue token when listing resources without namespace specified. This will cause when passing continue token, we always get the result of first page. Seems in makeClusterListCallBuilder() the continue param from ListOptions is never used.
=> fix: add missing continue token when build cluster list call

util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesListApiTest.java
Somehow the source code on master branch failed formatter check after merging in the folowing PR:
https://github.com/kubernetes-client/java/pull/3930
This PR straights the format.
=> Chore: Re-run spotless formatter

util/src/test/java/io/kubernetes/client/ExecTest.java
=> Switch to Countdown latch and actually use it for test.

util/src/test/java/io/kubernetes/client/ExecTest.java
- added multiple query params for header "command" header as WireMock supports it [now](https://github.com/wiremock/wiremock/pull/2110) 
- other minor cosmetic improvements
=> Improve ExecTest.java

pom.xml
Upgrade okhttp to 4.12.0
This should help address [this issue](https://github.com/square/okhttp/issues/7944) in the 19.0.x branch.
=> Cherry Pick Commit 74ac2d6 To Release-19

util/src/main/java/io/kubernetes/client/util/SSLUtils.java
Cherrypick changes from [3595](https://github.com/kubernetes-client/java/pull/3595/commits) into release-legacy-23 for #3994 
Dynamically load security providers using the Java Service Provider Interface.
This allows the user to pick the provider based upon the dependencies it has on its classpath.
=> feat: add support for other security providers on legacy-23 #3994

util/src/main/java/io/kubernetes/client/util/SSLUtils.java
Cherrypick changes from [3595](https://github.com/kubernetes-client/java/pull/3595/commits) into master-java8 for #3994
Dynamically load security providers using the Java Service Provider Interface.
This allows the user to pick the provider based upon the dependencies it has on its classpath.
=> feat: add support for other security providers on master-java8 #3994

.github/workflows/generate.yml
Use patch command instead of `git apply` to avoid the git conflict in the GH action for model generation:
> https://github.com/kubernetes-client/java/actions/runs/14861796504
```
bcd074aaeab5:java $ ls scripts/patches/*.diff | xargs  -I {}  patch -i {}
patching file 'kubernetes/src/main/java/io/kubernetes/client/openapi/JSON.java'
patching file 'kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1ListMeta.java'
patching file 'kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1Secret.java'
patching file 'kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1Status.java'
bcd074aaeab5:java$ git add *.java
...
```
cc @brendandburns
=> Use patch cmd instead of `git apply` for conflict toleration

.github/workflows/generate.yml
Fixes the github action failure:
> https://github.com/kubernetes-client/java/actions/runs/14987439252/job/42103899250
By adding `-p0` to the command:
```
File to patch: 
Skip this patch? [y] 
Skipping patch.
2 out of 2 hunks ignored
can't find file to patch at input line 15
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
```
=> Generate workflow: Adding -p0 param for stripping prefix for patch cmd

.github/workflows/generate.yml
This PR fixes the linux compatibility for `patch` command as github workflow is linux-based... My previous PRs are tested in mac environment so it didn't reproduce the interactive error from the last generate workflow:
```
Run ls scripts/patches/*.diff | xargs -I {} patch -p0 -i {}
ls scripts/patches/*.diff | xargs -I {} patch -p0 -i {}
git add *.java
git commit -s -m 'Applied patches under scripts/patches/*.diff'
shell: /usr/bin/bash -e {0}
env:
JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.15-6/x64
JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.15-6/x64
BRANCH: automated-generate-0b1f95cb
PROJECT_VERSION: [2](https://github.com/yue9944882/java/actions/runs/15144087833/job/42575359321#step:9:2)4.0.0-SNAPSHOT
can't find file to patch at input line 14 …
```
=> Fix patch workflow - fix linux patch command compatibility

.github/workflows/release.yml
Currently it's a pain to manually release new versions. The following is an example of what we manually did for releasing 24.0.0: > https://github.com/kubernetes-client/java/issues/4054#issuecomment-2898658603
```
1.33 Model regeneration PR: https://github.com/kubernetes-client/java/pull/4056
Cut release branch release-24
1.33 Model regeneration PR for legacy branch: https://github.com/kubernetes-client/java/pull/4059
Cut release branch release-legacy-24
Run release workflow for release-24: https://github.com/yue9944882/java/actions/runs/15217107346
Run release workflow for release-legacy-24: https://github.com/yue9944882/java/actions/runs/15218963083
Release 24.0.0 PR: https://github.com/kubernetes-client/java/pull/4062
Release 24.0.0-legacy PR: …
```
=> Use PAT_TOKEN instead of GH_TOKEN to automate PR

.github/workflows/generate.yml
Previously we have refactored the version-release workflow to onboard to PAT_TOKEN, this PR applies the same change to model generation PR so the model generation workflow can also be fully automated. An example workflow execution see: 
> Workflow: https://github.com/yue9944882/java/actions/runs/15719884145
> PR: https://github.com/yue9944882/java/pull/125
=> Use PAT_TOKEN for model-generate workflow

examples/examples-release-latest/pom.xml, examples/examples-release-latest/src/main/java/io/kubernetes/client/examples/EKSAuthenticationExample.java, pom.xml, util/pom.xml, util/src/main/java/io/kubernetes/client/util/credentials/EKSAuthentication.java, util/src/test/java/io/kubernetes/client/util/credentials/EKSAuthenticationTest.java
Migrate EKS authentication from AWS 1.x -> AWS 2.x
Fixes https://github.com/kubernetes-client/java/issues/4110
=> Migrate EKS authentication from AWS 1.x -> AWS 2.x

util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
Fix typo where .dryRun() was called twice instead of .fieldManager() in GenericKubernetesApi.makeClusterCreateCallBuilder method.
Fixes #4138
=> fix: correct fieldManager parameter in makeClusterCreateCallBuilder

util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
Since the ApiClient has another constructor: apiClient(OkHttpClient). It's useful to allowing user customize the argument. OkHttp also recommend user to reuse the client instance(to sharing the internal dispatchers and connection pool).
=> Add ApiClient in ClientBuilder

e2e/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/examples-release-20/pom.xml, examples/examples-release-latest/pom.xml, fluent/pom.xml, kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
Remove Unused declared dependencies found in pom.xml.
mvn dependency:analyze output All "[WARNING] Unused declared dependencies found" are not correct, 
few are required for compilation
=>  Remove Unused declared dependencies found in pom.xml #3891

pom.xml
Maven central has officially deprecated the legacy nexus publish endpoint `oss.sonatype.org` according to:
> https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#configuring-the-repository
This PR update the endpoint to fix the release job failure for 1.34 release.
=> Replace deprecated nexusUrl with the new endpoint
