examples/README.md, examples/pom.xml, examples/src/main/java/io/kubernetes/client/examples/Example.java, pom.xml
=> Add a very simple example.

kubernetes/src/main/java/io/kubernetes/client/util/Config.java
@lavalamp @mbohlool roughly patterned off of `rest.Config` in `client-go`
=> Add a Config object that knows how to create ApiClients

.gitignore
* Ignore vs-code IDE files
* Ignore maven `target` directories
=> Update the gitignore file.

util/src/main/java/io/kubernetes/client/util/Config.java
=> Add a bunch of simplified helper methods for creating clients from different information.

examples/pom.xml, examples/src/main/java/io/kubernetes/client/examples/Example.java, kubernetes/.swagger-codegen-ignore, kubernetes/src/main/java/io/kubernetes/client/ApiClient.java, util/pom.xml, util/src/main/java/io/kubernetes/client/util/Config.java, util/src/main/java/io/kubernetes/client/util/KubeConfig.java, util/src/main/java/io/kubernetes/client/util/SSLUtils.java
=> Add support for kubeconfig based client creation.

util/src/main/java/io/kubernetes/client/util/KubeConfig.java
Requested in #17 
@mbohlool 
Thanks!
=> Remove some extraneous error lines.

util/src/main/java/io/kubernetes/client/util/Config.java
Closes https://github.com/kubernetes-client/java/issues/22
Sorry for the beginner question: how do I setup a test environment to verify this patch locally?
=> Base64 decode CA Cert from kubeconfig

examples/src/main/java/io/kubernetes/client/examples/Example.java, kubernetes/src/main/java/io/kubernetes/client/ApiClient.java, util/src/main/java/io/kubernetes/client/util/Config.java, util/src/main/java/io/kubernetes/client/util/KubeConfig.java
@mbohlool 
Fixes #29 
Fixes some bugs I discovered while testing auth...
=> Fix up auth a little bit.

.gitignore, util/src/main/java/io/kubernetes/client/util/KubeConfig.java, util/src/test/java/io/kuberentes/client/util/ConfigTest.java, util/src/test/java/io/kuberentes/client/util/KubeConfigTest.java
=> Add support for tokenFile in KubeConfig, fix up/add some tests.

kubernetes/pom.xml
Let me know if these changes are accurate.
=> Update POM to reflect License & Authors

examples/src/main/java/io/kubernetes/client/examples/WatchExample.java, kubernetes/src/main/java/io/kubernetes/client/ApiClient.java, util/src/main/java/io/kubernetes/client/util/Watch.java
Watch class should be in util package.
=> Move Watch to util package

examples/src/main/java/io/kubernetes/client/examples/Example.java, util/pom.xml, util/src/main/java/io/kubernetes/client/Exec.java, util/src/main/java/io/kubernetes/client/util/Config.java, util/src/main/java/io/kubernetes/client/util/KubeConfig.java, util/src/main/java/io/kubernetes/client/util/SSLUtils.java, util/src/main/java/io/kubernetes/client/util/WebSockets.java, util/src/main/java/io/kubernetes/client/util/authenticators/GCPAuthenticator.java, util/src/main/resources/log4j.properties
Intellij also sorted some imports in the process.
=> Use log4j for logging exceptions

kubernetes/RELEASES.md, kubernetes/pom.xml
=> Document release process using maven-release-plugin

kubernetes/RELEASES.md, pom.xml
=> Configure GPG artifact signing

examples/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, util/pom.xml
Closes https://github.com/kubernetes-client/java/issues/64
=> Rename parent POM & util POM to make client-java the primary artifact name

util/src/main/java/io/kubernetes/client/util/Config.java
=> Fix the cluster initialization of the client.

examples/Dockerfile, examples/pom.xml
@lwander @mbohlool 
Useful for testing in clusters.
=> Generate a jar with dependencies and build a Dockerfile for it.

README.md, examples/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, util/pom.xml, util/src/main/java/io/kubernetes/client/Exec.java, util/src/main/java/io/kubernetes/client/ProtoClient.java
All [maven-release-plugin] commits were auto generated.
=> Release 0.2

util/src/main/java/io/kubernetes/client/util/Config.java
=> Add a URL prefix if one is missing.

README.md
=> Fix support/capabilities' badge links

util/src/main/java/io/kubernetes/client/util/Watch.java
=> add close to watch

util/src/main/java/io/kubernetes/client/util/WebSockets.java
See https://github.com/kubernetes-client/java/issues/122 .
=> fixed WebSockets message types: binary vs text

kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java
fix for issue https://github.com/kubernetes-client/java/issues/126
=> adding toString method to IntOrString

util/src/main/java/io/kubernetes/client/util/KubeConfig.java, util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java
Fixes https://github.com/kubernetes-client/java/issues/145
Fixes #147 
@allen-servedio
=> Add code for extracting the current namespace.

README.md
Doc in the readme is not aligned to example.
=> Align documentation to actual code

examples/src/main/java/io/kubernetes/client/examples/WebSocketsExample.java
Fixes #151 
@mbohlool @lwander
=> Add better docs to the WebSocket example.

examples/src/main/java/io/kubernetes/client/examples/PortForwardExample.java, util/src/main/java/io/kubernetes/client/PortForward.java
=> Fix code that didn't follow the stream protocol.

RELEASES.md
=> Fix code formatting in releases.md

CHANGELOG.md
=> Add changelog for 1.0.0-beta2

README.md
[Example class here](https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/Example.java)
=> Fixed listPodForAllNamespaces to follow along with the actual Example class

util/src/main/java/io/kubernetes/client/PortForward.java
This PR addresses the issue described in issue #214 .
=> Fix issue #214

util/src/main/java/io/kubernetes/client/Exec.java, util/src/main/java/io/kubernetes/client/KubernetesConstants.java, util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
Final review comment edits to the recent Exec work that missed the previous pull request.
=> Minor cleanups to Exec

CHANGELOG.md, README.md
@lwander @lewisheadden @rjeberhard
=> Propose release 1.0.0-beta3

kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java
Adding single argument constructor in Quantity class, because of this issue : [issue](https://github.com/kubernetes-client/java/pull/207#issuecomment-376148470)
=> add single argument constructor in Quantity

examples/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, util/pom.xml
This is already pushed so I'm going to merge on green.
=> client-1.0.0-beta4 release.

README.md, examples/src/main/java/io/kubernetes/client/examples/ExecExample.java
fix spelling in ExecExample.java
=> add Exec to comment

util/src/main/java/io/kubernetes/client/Exec.java
fixes issue https://github.com/kubernetes-client/java/issues/257 by performing URLEncoder.encode on list of commands
=> fix for exec command encoding issue

examples/pom.xml, util/pom.xml
=> Update Guava dependency.

util/src/main/java/io/kubernetes/client/util/Yaml.java, util/src/test/java/io/kubernetes/client/util/YamlTest.java, util/src/test/resources/test.yaml
Loading secrets from YAML files was failing for me. Let me know if this change is the right way to fix that, thanks!
=> Correctly load base64-encoded strings from Secret Yaml files.

util/src/main/java/io/kubernetes/client/util/ClientBuilder.java, util/src/main/java/io/kubernetes/client/util/ConfigPersister.java, util/src/main/java/io/kubernetes/client/util/FilePersister.java, util/src/main/java/io/kubernetes/client/util/KubeConfig.java, util/src/test/java/io/kubernetes/client/ExecTest.java, util/src/test/java/io/kubernetes/client/util/FilePersisterTest.java, util/src/test/resources/kubeconfig-http
=> Add config file persistence.

util/src/main/java/io/kubernetes/client/util/Watch.java
=> Close watches more cleanly.

CHANGELOG.md, examples/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, util/pom.xml
=> Release 3.0.0-beta1

SECURITY_CONTACTS
Closes #277 
@jessfraz
@lwander (since I volunteered him...)
=> Add security contacts.

util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java, util/src/test/java/io/kubernetes/client/util/ConfigTest.java
=> Clear KUBECONFIG env variable before tests.

examples/pom.xml, util/pom.xml
Hi please,
review my commit. With this PR I try to fix build on master
Thanks for attention
=> Use project version instead of directly reference

kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java
=> Implemented equals method for Quantity

util/src/main/java/io/kubernetes/client/util/SSLUtils.java
Support client certificate chain as described in 7.4.6 of [rfc5246](https://tools.ietf.org/html/rfc5246#section-7.4.6).
=> support client certificate chain

examples/pom.xml, examples/src/main/java/io/kubernetes/client/examples/Example.java, examples/src/main/java/io/kubernetes/client/examples/ExpandedExample.java
I wrote the more example for the k8s Java Client with Java SE 8 Lambda expression.
This example will execute and show following in one example.
1.  scale the number of pod
2.  show all namespaces and pods in specific namespace
3.  show Services
4.  show logs for specific pod
Please refer to the following execution logs in my environment?
[log.txt](https://github.com/kubernetes-client/java/files/2342448/log.txt)
And I will add the diff as follows.
[diff.txt](https://github.com/kubernetes-client/java/files/2344049/diff.txt)
Thank you & Best Regards.
Yoshio.
=> Added more example with Java SE 8 Lambda expression

util/src/main/java/io/kubernetes/client/util/Yaml.java, util/src/test/java/io/kubernetes/client/util/YamlTest.java
fixes https://github.com/kubernetes-client/java/issues/368
=> add constructDateTime to snakeYaml CustomConstructor

examples/src/main/java/io/kubernetes/client/examples/ParseExample.java, kubernetes/pom.xml
=> Add an example of how to parse and generate JSON.

CHANGELOG.md, examples/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, util/pom.xml
@lwander if you have a chance to review....
=> Release 3.0.0-beta2

util/src/main/java/io/kubernetes/client/util/KubeConfig.java
=> Changed to set USERPROFILE on Windows environment.

util/pom.xml
@kondapally1989 
First step in better test coverage is measuring our coverage!
=> Add coverage reporting to util pom.xml

examples/pom.xml, examples/src/test/java/io/kubernetes/client/examples/ExampleTest.java
=> Add a simple example test.

README.md, examples/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, util/pom.xml
=> Release 3.0.0

kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java
Indent two spaces instead of four to be consistent with the rest
of this project.
=> Fix formatting in Quantity.java

kubernetes/src/test/java/io/kubernetes/client/JSONTest.java, kubernetes/src/test/java/io/kubernetes/client/custom/SuffixFormatterTest.java, kubernetes/src/test/java/io/kubernetes/client/models/V1PodBuilderTest.java
* JSONTest
* SuffixFormatterTest
* V1PodBuilderTest
Indent two spaces instead of four to be consistent with the rest
of this project.
=> Use two space indentation in some test classes

examples/pom.xml, examples/src/test/java/io/kubernetes/client/examples/ExampleTest.java, util/pom.xml, util/src/main/java/io/kubernetes/client/Copy.java, util/src/main/java/io/kubernetes/client/Exec.java, util/src/main/java/io/kubernetes/client/PodLogs.java, util/src/test/java/io/kubernetes/client/AttachTest.java, util/src/test/java/io/kubernetes/client/CopyTest.java, util/src/test/java/io/kubernetes/client/ExecTest.java, util/src/test/java/io/kubernetes/client/PodLogsTest.java, util/src/test/java/io/kubernetes/client/PortForwardTest.java, util/src/test/java/io/kubernetes/client/util/YamlTest.java
=> Improve unit test coverage

examples/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, util/pom.xml
@cliveseldon please take a look.
Thanks!
=> Release 4.0.0-beta1

util/src/main/java/io/kubernetes/client/util/KubeConfig.java, util/src/main/java/io/kubernetes/client/util/authenticators/AzureActiveDirectoryAuthenticator.java, util/src/main/java/io/kubernetes/client/util/authenticators/GCPAuthenticator.java, util/src/test/java/io/kubernetes/client/util/FilePersisterTest.java, util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java
Added some minor code improvements and added unit test coverage to ensure safety.
=> minor code fixes and unit tests added to KubeConfig

util/src/main/java/io/kubernetes/client/PortForward.java, util/src/main/java/io/kubernetes/client/ProtoClient.java
Add the missing boilerplate file
=> add the boilerplate file

.travis.yml, util/src/main/java/io/kubernetes/client/util/authenticators/GCPAuthenticator.java, util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java
=> Improve auth tests, fix a bug in credential parsing

util/src/main/java/io/kubernetes/client/util/Yaml.java, util/src/test/java/io/kubernetes/client/util/YamlTest.java, util/src/test/resources/test-pod.yaml
=> Fix DateTime string generation.

examples/createPod.sh
=> Improve script a little bit.

OWNERS
=> Updated OWNERS to include link to docs

examples/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, util/pom.xml
=> Release 4.0.0

util/src/main/java/io/kubernetes/client/util/Watch.java, util/src/test/java/io/kubernetes/client/util/WatchTest.java
Fixes #516 
@rjeberhard @kondapally1989
=> Fix some problems with watches that return a v1.Status

kubernetes/src/main/java/io/kubernetes/client/ApiClient.java, util/src/main/java/io/kubernetes/client/util/ClientBuilder.java, util/src/main/java/io/kubernetes/client/util/ProxyContentTypeRequestBody.java, util/src/test/java/io/kubernetes/client/util/ClientBuilderPatchTest.java, util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
=> Fixes patch format to support various patch formats

util/src/main/java/io/kubernetes/client/util/ProxyContentTypeRequestBody.java
apologises for carelessness, it's somehow generated by my IDE tooling 😥
/cc @brendandburns @kondapally1989
=> Remove unexpected boilerplate headers

OWNERS
I'm stably working on SIG API-Machinery especially server-side features and extensibility including both UAS/AA and TPR/CRD by maintaining multiple related subjects. I'm familiar w/ the kubernetes api stuff and love programming multilingually so volunteering adding myself as a part-time maintainer assisting running this repo. 
/assign @mbohlool  @brendandburns
=> Add yue to java maintainer

util/pom.xml
=> Update org.bouncycastle dependency #554

CHANGELOG.md, README.md
=> Improve documentation of potential breaking changes. Add changelog for 4.0.0

examples/pom.xml, extended/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, util/pom.xml
@yue9944882 
release 5.0.0 has been pushed to Sonatype and should be duplicated to maven central in 24hr or so...
=> Release 5.0

examples/src/main/java/io/kubernetes/client/examples/InformerExample.java, examples/src/main/java/io/kubernetes/client/examples/WatchExample.java
Informer will retry list and watch when read timeout, better to add it to example...
=> Add timeout configuration to InformerExample

util/src/main/java/io/kubernetes/client/informer/cache/Controller.java, util/src/test/java/io/kubernetes/client/informer/SharedInformerFactoryTest.java
Fixes: #578
/cc @cizezsy @brendandburns
=> Bugfix: Shut down reflector daemon job gracefully

kubernetes/src/main/java/io/kubernetes/client/custom/V1Patch.java
=> Follow-up of #587: addressing minor comments

util/pom.xml
=> Chore: Exclude embeded dependencies from bundle packaging

examples/src/main/java/io/kubernetes/client/examples/LeaderElectionExample.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElectionConfig.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElectionRecord.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/Lock.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/ConfigMapLock.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/EndpointsLock.java, extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectionTest.java, util/src/main/java/io/kubernetes/client/util/leaderelection/LeaderElectionConfig.java, util/src/main/java/io/kubernetes/client/util/leaderelection/LeaderElectionRecord.java, util/src/main/java/io/kubernetes/client/util/leaderelection/LeaderElector.java, util/src/main/java/io/kubernetes/client/util/leaderelection/Lock.java, util/src/main/java/io/kubernetes/client/util/leaderelection/resourcelock/ConfigMapLock.java, util/src/main/java/io/kubernetes/client/util/leaderelection/resourcelock/EndpointsLock.java, util/src/test/java/io/kubernetes/client/util/leaderelection/LeaderElectionTest.java
Leader election for #523
Please take a look @yue9944882
=> leader election

kubernetes/src/main/java/io/kubernetes/client/ApiClient.java, util/src/test/java/io/kubernetes/client/util/ClientBuilderPatchTest.java
=> Chore: Remove duplicated patch format from ApiClient

util/src/main/java/io/kubernetes/client/util/Yaml.java
Signed-off-by: runzexia <runzexia@yunify.com>
=> add v2beta2 apiversion for autoscaling/v2beta2/hpa

README.md, examples/src/main/java/io/kubernetes/client/examples/InClusterClientExample.java, examples/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java
=> Chore: Add [in|out-of] cluster examples and enhance docs

docs/generate-model-from-third-party-resources.md
=> Doc: Generate model from third-party-resources

README.md, examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java, extended/src/main/java/io/kubernetes/client/extended/controller/Controller.java, extended/src/main/java/io/kubernetes/client/extended/controller/ControllerManager.java, extended/src/main/java/io/kubernetes/client/extended/controller/Controllers.java, extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java, extended/src/main/java/io/kubernetes/client/extended/controller/LeaderElectingController.java, extended/src/main/java/io/kubernetes/client/extended/controller/WorkQueueResourceEventHandler.java, extended/src/main/java/io/kubernetes/client/extended/controller/builder/Constants.java, extended/src/main/java/io/kubernetes/client/extended/controller/builder/ControllerBuilder.java, extended/src/main/java/io/kubernetes/client/extended/controller/builder/ControllerManangerBuilder.java, extended/src/main/java/io/kubernetes/client/extended/controller/builder/DefaultControllerBuilder.java, extended/src/main/java/io/kubernetes/client/extended/controller/reconciler/Reconciler.java, extended/src/main/java/io/kubernetes/client/extended/controller/reconciler/Request.java, extended/src/main/java/io/kubernetes/client/extended/controller/reconciler/Result.java, extended/src/test/java/io/kubernetes/client/extended/controller/ControllerManagerTest.java, extended/src/test/java/io/kubernetes/client/extended/controller/DefaultControllerTest.java, extended/src/test/java/io/kubernetes/client/extended/controller/LeaderElectingControllerTest.java, extended/src/test/java/io/kubernetes/client/extended/controller/WorkQueueResourceEventHandlerTest.java, extended/src/test/java/io/kubernetes/client/extended/controller/builder/DefaultControllerBuilderTest.java
=> Out-of-box controller runtime framework and builder library

README.md
=> Docs: Note examples' supported release version

examples/src/main/java/io/kubernetes/client/examples/PatchExample.java, kubernetes/src/main/java/io/kubernetes/client/custom/V1Patch.java
Signed-off-by: runzexia <runzexia@yunify.com>
=> serverside apply & example

util/src/main/java/io/kubernetes/client/informer/cache/Controller.java, util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java
ref: #656 (will close it after the issue is confirmed completely solved)
/cc @brendandburns
=> Fixes leaking informer#controller daemon thread

util/src/main/java/io/kubernetes/client/informer/cache/ProcessorListener.java
/cc @brendandburns 
bugfix: listener thread can quit unexpectedly leaves queue growing to OOM..
=> Fixes unexpectedly listener quitting leads to OOM

examples/pom.xml, extended/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, util/pom.xml
=> Release 6.0

util/src/main/java/io/kubernetes/client/util/SSLUtils.java
Possible fix for https://github.com/kubernetes-client/java/issues/676
=> 676 - fix for EC cert loading exception

extended/src/main/java/io/kubernetes/client/extended/workqueue/DefaultRateLimitingQueue.java
`new DefaultRateLimitingQueue()` should create a RateLimiter...
=> Fix: add lacked ratelimiter initialization

util/src/main/java/io/kubernetes/client/PortForward.java
=> Fix a bug where the error stream for port forwarding was an input stream

util/src/main/java/io/kubernetes/client/Copy.java
Closes #681 
We should really expand tests for this code, I'll do it in a different PR.
=> Fix a dropped parameter.

util/src/main/java/io/kubernetes/client/Exec.java, util/src/test/java/io/kubernetes/client/CopyTest.java, util/src/test/java/io/kubernetes/client/ExecTest.java
=> Fix exec to look up container name if absent.

examples/src/main/java/io/kubernetes/client/examples/WebSocketsExample.java, util/src/main/java/io/kubernetes/client/Copy.java, util/src/main/java/io/kubernetes/client/Exec.java, util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java, util/src/main/java/io/kubernetes/client/util/WebSockets.java, util/src/test/java/io/kubernetes/client/ExecTest.java
Fixes #686 
cc @ceeaspb please see if this addresses your issue.
=> Fix error handling.

util/src/main/java/io/kubernetes/client/Copy.java, util/src/main/java/io/kubernetes/client/Exec.java, util/src/main/java/io/kubernetes/client/util/Watch.java, util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java, util/src/main/java/io/kubernetes/client/util/WebSockets.java
Possible fixes for #687 
@ceeaspb
=> Improve close behavior some.

util/src/main/java/io/kubernetes/client/Copy.java, util/src/test/java/io/kubernetes/client/CopyTest.java
There are utilities copying files from a pod, but it is missing transferring files to a pod. Added a method transferring a file to a pod.
Issue #353
=> Implement copyFileToPod

util/src/main/java/io/kubernetes/client/util/ClientBuilder.java, util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
- Sets the correct config file when using Home Directory
- Added a test case as well
Fix #668
=> Set config file when using home directory

examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java, examples/src/main/java/io/kubernetes/client/examples/LeaderElectionExample.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java, extended/src/test/java/io/kubernetes/client/extended/controller/LeaderElectingControllerTest.java, extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectionTest.java
Fix #706
this pr fix the same issue as #708 , cause I think #708 got some misunderstanding with "renewDeadline".
=> "renewDeadline" support for leader election

util/pom.xml
Closes a potential DoS attack in Compress `1.18`
=> Upgrade Apache Compress 1.19

util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
Removing duplicate code snippet. Please take a look.
=> Refactor: removing duplicate code snippet

README.md, examples/src/main/java/io/kubernetes/client/examples/YamlExample.java, examples/test-svc.yaml
=> Added example for create StatefulSet from file

util/src/test/java/io/kubernetes/client/CopyTest.java
=> Ignore the flaking CopyTest w/ TODO comment left

util/src/main/java/io/kubernetes/client/util/Config.java
Looked at another TODO. Adding UTF-8 support in Config class.
=> UTF-8 support for config class

client-java-osgi/bnd.bnd, client-java-osgi/pom.xml, pom.xml
This is a followup of #744 
The same code but rebased on top of `release-6.0` branch.
=> Dedicated OSGi bundle merging both `client-java` and `client-java-api`

util/src/main/java/io/kubernetes/client/Copy.java, util/src/test/java/io/kubernetes/client/CopyTest.java
Very small change. This is for another TODO comment.
=> Using GzipCompressorInputStream for decompressing .gz files.

examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java
=> Doc: Emphasis setting infinite timeout in controller example

util/src/main/java/io/kubernetes/client/util/labels/EqualityMatcher.java, util/src/main/java/io/kubernetes/client/util/labels/LabelMatcher.java, util/src/main/java/io/kubernetes/client/util/labels/LabelSelector.java, util/src/main/java/io/kubernetes/client/util/labels/SetMatcher.java, util/src/test/java/io/kubernetes/client/util/labels/LabelSelectorTest.java
=> Feat: Fundamental label selector utils

README.md
=> Modify Incorrect URL address

util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Add a new construction method for customization
=> Constructs informer by setting lister-watcher from InformerFactory

util/src/main/java/io/kubernetes/client/util/PatchUtils.java, util/src/test/java/io/kubernetes/client/util/PatchUtilsTest.java
=> Introduce oneline patch util for overriding patch format from generated client

examples/src/main/java/io/kubernetes/client/examples/PatchExample.java
/cc @brendandburns 
follow-up of #827
=> Update patch example to reflect usage of PatchUtil

util/src/main/java/io/kubernetes/client/util/ClientBuilder.java, util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
Fixes: #839 
/cc @brendandburns @liggitt
=> Bugfix: Fixes ipv6 host support

extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java, extended/src/main/java/io/kubernetes/client/extended/wait/Wait.java
=> Bugfix: Eliminate initial delay of ready check

extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
or else java application doesn't successfully exit  on finishing main() method.
~~TODO:  Figuring out CLA signing  details shortly.~~
=> make background threads in LeaderElector to be daemon

extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java, extended/src/test/java/io/kubernetes/client/extended/generic/GenericKubernetesApiForCoreApiTest.java
=> Unchain core/v1 resources for generic kubernetes client

extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java, extended/src/test/java/io/kubernetes/client/extended/generic/GenericKubernetesApiForCoreApiTest.java, extended/src/test/java/io/kubernetes/client/extended/generic/GenericKubernetesApiTest.java, pom.xml, spring/pom.xml, spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java, spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java, spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/GroupVersionResource.java, spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesInformer.java, spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesInformers.java, spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconciler.java, spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerReadyFuncs.java, spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerWatch.java, spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerWatches.java, spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerWorkerCount.java, spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java, spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerCreatorTest.java, spring/src/test/java/io/kubernetes/client/spring/extended/controller/TestApplication.java, spring/src/test/resources/spring/test-context.xml
=> Spring integration: IoC injection for kubernetes informer/reconciler

util/pom.xml
=> Update bouncy castle dependency to 1.64

spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java
=> Fixes work-queue injection for spring integration

.github/workflows/maven.yml
=> Setup GH action CI flow

spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java
=> Fixes unit-test CI failure

examples/pom.xml, extended/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring/pom.xml, util/pom.xml
This has already been pushed out to sonatype.
Fixes #945
=> Merge changes for the 8.0.1 release

extended/src/main/java/io/kubernetes/client/extended/event/legacy/LegacyEventBroadcaster.java, extended/src/main/java/io/kubernetes/client/extended/event/legacy/ObjectReferenceResolvingEventRecorder.java
=> Fixes event-recorder event-source setting

examples/pom.xml, extended/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring/pom.xml, util/pom.xml
Fixes #951 
This has been pushed out to Sonatype
@yue9944882
=> Release 8.0.2

README.md
=> Refresh README for latest release 8.0.2

spring/pom.xml
Fixes #934 (I think)
cc @yue9944882
=> Bring spring integration pom inline with other poms.

extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java, extended/src/test/java/io/kubernetes/client/extended/controller/DefaultControllerTest.java
=> Catches runtime-exception upon executing reconciler

util/src/main/java/io/kubernetes/client/informer/EventType.java, util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
=> Supporting "BOOKMARK" watch event-type

README.md, examples/src/main/java/io/kubernetes/client/examples/GenericClientExample.java, extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java
/cc @brendandburns 
the generic client has been working/verified for releases, promoting it to the example list
=> Generic kubernetes client example

util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
this pull help exposes stack-traces in the error log
=> Chore: Enhances ReflectorRunner error log

.github/dependabot.yml
reference:
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
=> add dependabot.yml for dependency management

README.md
This PR adds syntax highlights to the README
=> Chore: Docs java highlights

examples/src/main/java/io/kubernetes/client/examples/LeaderElectionExample.java
=> Revises leader election example for clarification

README.md
=> Clarifying requirement for extended module in the example list

pom.xml, util/src/main/java/io/kubernetes/client/util/ClientBuilder.java, util/src/main/java/io/kubernetes/client/util/KubeConfig.java, util/src/main/java/io/kubernetes/client/util/credentials/KubeconfigAuthentication.java
=> Add relative path loading for certificates.

extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java, extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectionTest.java
this pull picks `OnNewLeader` callback for leader elector from golang library:
https://github.com/kubernetes/kubernetes/blob/a138be8722ebd0ce281029fa747315500a99ffd5/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L169-L172
=> Support on-new-leader hook for leader elector

proto/pom.xml
@brendandburns is this module skipped intentionally?
=> Prune "skip" configuration for deploying proto module

pom.xml
Fix for #1032 . It will also help issues on other OS platforms.
/assign @brendandburns
=> Fixing build error that is thrown with Java 11 and above

util/src/main/java/io/kubernetes/client/ProtoClient.java
Found another code fragment which can be extracted as method.
=> Removing duplicate code

util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java, util/src/test/java/io/kubernetes/client/util/PatchUtilsTest.java
I have added 2 changes:
1. Removed unused imports
2. Added missing log parameter for placeholder
=> Removing unused imports and adding a log parameter for placeholder

examples/src/main/java/io/kubernetes/client/examples/ExecExample.java, util/src/main/java/io/kubernetes/client/Copy.java, util/src/main/java/io/kubernetes/client/PortForward.java, util/src/main/java/io/kubernetes/client/informer/cache/SharedProcessor.java
=> Clean up the code

util/src/main/java/io/kubernetes/client/informer/cache/Cache.java
Remove the lock and make methods synchronized
=> Remove the lock and make methods synchronized

util/src/main/java/io/kubernetes/client/Copy.java, util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java, util/src/test/java/io/kubernetes/client/util/YamlTest.java
Summary of changes:
1. Removing redundant return statement
2. Replacing numeric check with Math.max
3. Ending long variable with 'L' for better readability
=> Code clean up.

util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java, util/src/test/java/io/kubernetes/client/util/credentials/AccessTokenAuthenticationTest.java, util/src/test/java/io/kubernetes/client/util/credentials/UsernamePasswordAuthenticationTest.java
This as per below link:
[Deprecated classes](https://junit.org/junit4/javadoc/latest/deprecated-list.html)
=> Removing deprecated class in Junit

util/src/test/java/io/kubernetes/client/util/YamlTest.java
=> Removing deprecated API

examples/src/main/java/io/kubernetes/client/examples/ExpandedExample.java, examples/src/main/java/io/kubernetes/client/examples/PatchExample.java
=> Switiching to apps/v1 deployment api in the examples

util/src/main/java/io/kubernetes/client/informer/cache/SharedProcessor.java, util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java
Use the shutdown pattern in https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html
=> Gracefully shutdown listener pool

examples/pom.xml, extended/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring/pom.xml, util/pom.xml
This has been pushed out to Sonatype.
Closes #1050
=> Release 9.0.0

util/src/main/java/io/kubernetes/client/util/version/Version.java, util/src/test/java/io/kubernetes/client/util/version/VersionTest.java
My local workspace got corrupted. So created new PR.
=> Adding utility to get K8 version

settings
consumer part of https://github.com/kubernetes-client/gen/pull/168
this pull will properly format the default user-agent
=> Code generation: Refresh client version

extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
Once created, `LeaderElector` will never release thread pools. In some environments this prevents JVM shutdown and causes memory leak.
=> Provide standard method to cleanup schedulers

examples/src/main/java/io/kubernetes/client/examples/LeaderElectionExample.java
=> Leader election autoclosable example

examples/src/main/java/io/kubernetes/client/examples/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlScale.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlVersion.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlScaleTest.java
=> Add an implementation of kubectl scale.

scripts/update-client.sh
- errors should go to stderr
- exit with no arguments takes the previous command exit code, so it wasking the exit code from the echo command.
- Using $(...) instead of `` which is way better.
=> Little improvements to the update client script

examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlExec.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlScale.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlScaleTest.java
cc @yue9944882 part of #1072 
Please check out the refactor, I think it will make it easier/more consistent to add future commands.
=> Clean up/refactor kubectl to share some code and add kubectl exec.

examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLog.java
=> Implement Kubectl Log

util/src/main/java/io/kubernetes/client/informer/cache/SharedProcessor.java, util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java
=> Graceful shutdown sharedprocessor

util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java, util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java
=> Fix generic watches, add test.

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/library-scripts/README.md, .devcontainer/library-scripts/common-debian.sh, .devcontainer/library-scripts/node-debian.sh, .devcontainer/maven-settings.xml
See details here:
https://docs.github.com/en/github/developing-online-with-codespaces/configuring-codespaces-for-your-project
=> Add devcontainer for github codespaces.

extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlAnnotate.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java
share more codes in the resource builder
=> Promote apiGroup/apiVersion/resourceName to resourceBuilder

examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java, examples/src/main/java/io/kubernetes/client/examples/PortForwardExample.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlExec.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPortForward.java, util/src/main/java/io/kubernetes/client/PortForward.java, util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java, util/src/test/java/io/kubernetes/client/PortForwardTest.java
=> Add port forward to kubectl

examples/pom.xml, extended/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring/pom.xml, util/pom.xml
cc @yue9944882 
This has been pushed out to sonatype, should be replicated to maven central in ~1 day.
=> Release 9.0.1

examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlApiResources.java, util/src/main/java/io/kubernetes/client/Discovery.java, util/src/test/java/io/kubernetes/client/DiscoveryTest.java
this pull implements client-side api-discovery and `kubectl api-resources` equivalence
=> kubectl(api-resources): api discovery implementation

util/src/main/java/io/kubernetes/client/Copy.java, util/src/test/java/io/kubernetes/client/CopyTest.java
An overloading copy to pod method which would allow us to perform a copy using an in memory src byte array resource.
The existing copy to pod method expects the file to exist physically in the src pod as it uses `FileInputStream` internally,
the second method added in this PR does not.
=> add overloading method to copy in memory binary data to pod

examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCopy.java
=> Add support for KubectlCopy.

examples/src/main/java/io/kubernetes/client/examples/MetricsExample.java, kubernetes/src/main/java/io/kubernetes/client/custom/NodeMetrics.java, kubernetes/src/main/java/io/kubernetes/client/custom/NodeMetricsList.java, util/src/main/java/io/kubernetes/client/Metrics.java
cc @yue9944882 
I'll do Pod Metrics next, and then `kubectl top`
=> Add node metrics helper utilities.

util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
=> Doc: Fixes the gap between doc & impl for informer factory

examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlTaint.java, util/src/main/java/io/kubernetes/client/util/taints/Taints.java, util/src/test/java/io/kubernetes/client/util/taints/TaintsTest.java
=> Add support for taints and kubectl taint.

examples/pom.xml, examples/src/main/java/io/kubernetes/client/examples/PrometheusExample.java, util/pom.xml, util/src/main/java/io/kubernetes/client/monitoring/Monitoring.java, util/src/main/java/io/kubernetes/client/monitoring/PrometheusInterceptor.java
=> Add utilities for instrumentation.

examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlTop.java
=> Add an initial implementation of top

util/src/main/java/io/kubernetes/client/util/authenticators/OpenIDConnectAuthenticator.java, util/src/main/java/io/kubernetes/client/util/credentials/UsernamePasswordAuthentication.java, util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java, util/src/test/java/io/kubernetes/client/util/credentials/OpenIDConnectAuthenticationTest.java
Replacing few strings with Standard constants.
=> Clean up- adding Standard Charset constant

examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCordon.java
=> Add support for kubectl cordon.

util/src/main/java/io/kubernetes/client/informer/cache/DeltaFIFO.java, util/src/main/java/io/kubernetes/client/util/ModelMapper.java, util/src/main/java/io/kubernetes/client/util/Watch.java, util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java, util/src/main/java/io/kubernetes/client/util/Yaml.java, util/src/main/java/io/kubernetes/client/util/authenticators/OpenIDConnectAuthenticator.java, util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java, util/src/main/java/io/kubernetes/client/util/taints/Taints.java, util/src/test/java/io/kubernetes/client/util/TestUtils.java, util/src/test/java/io/kubernetes/client/util/YamlTest.java
Following clean up:
1. Removed unnecessary semicolon.
2. Wildcard type argument ? explicitly extends Object class
3. Simplified if-else
4. Removed redundant variables
=> Clean up various files

e2e/pom.xml, pom.xml
Update of #1198 with test fixes.
=> Update gmaven-plus version.

util/src/main/java/io/kubernetes/client/Attach.java, util/src/main/java/io/kubernetes/client/util/ConfigPersister.java, util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java, util/src/main/java/io/kubernetes/client/util/WebSockets.java, util/src/main/java/io/kubernetes/client/util/authenticators/Authenticator.java, util/src/main/java/io/kubernetes/client/util/taints/Taints.java
Following changes:
1. Removed the exception that is never thrown.
2. 'public' modifier for interface methods is redundant.
3. 'static' modifier for enum is redundant for inner enum.
=> Code clean up

examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCordon.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDrain.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlDrainTest.java, extended/src/test/resources/pod-list.json
=> Add kubectl drain.

util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
=> flush stream after WebSocket handleMessage

client-java-contrib/cert-manager/update.sh, docs/generate-model-from-third-party-resources.md, scripts/publish-crd-model-gen-image.sh
/cc @brendandburns @simingweng
=> Publishes and documents crd-model-gen images

OWNERS
=> Move mbohlool to emeritus status.

docs/generate-model-from-third-party-resources.md
=> CodeGen doc follow-up

util/src/test/java/io/kubernetes/client/CopyTest.java
Switching to semaphores made the test more flaky. I think this is because we've got the same port for all tests (I think) switch to dynamic ports is a good idea anyway.
=> Change wiremock to use dynamic ports.

util/src/test/java/io/kubernetes/client/AttachTest.java, util/src/test/java/io/kubernetes/client/DiscoveryTest.java, util/src/test/java/io/kubernetes/client/ExecTest.java, util/src/test/java/io/kubernetes/client/PodLogsTest.java, util/src/test/java/io/kubernetes/client/PortForwardTest.java
=> Change a bunch of tests to use dynamic ports for wire mocks.

extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/ConfigMapLock.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/EndpointsLock.java
Fixes #1200 
CLA signature still pending. Working on it.
=> Improve logging in leader election

util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerTest.java, util/src/test/java/io/kubernetes/client/util/PatchUtilsTest.java, util/src/test/java/io/kubernetes/client/util/credentials/TokenFileAuthenticationTest.java, util/src/test/java/io/kubernetes/client/util/version/VersionTest.java
=> Removing static port in Junit tests

util/src/test/java/io/kubernetes/client/CopyTest.java
This reverts commit 07376cdd3dad5309c25ff790e880030d76d1974b.
=> Fixes failing test: Sleep 2s before verfication

util/src/test/java/io/kubernetes/client/AttachTest.java, util/src/test/java/io/kubernetes/client/DiscoveryTest.java, util/src/test/java/io/kubernetes/client/ExecTest.java, util/src/test/java/io/kubernetes/client/PodLogsTest.java, util/src/test/java/io/kubernetes/client/PortForwardTest.java
More flake reduction (I hope) move away from the default wireMock to the test specific `wireMockRule`
=> Move away from static wire mocks.

util/src/main/java/io/kubernetes/client/util/ModelMapper.java
Switch `BiDirectionalMap` to use a striped lock for better concurrency on par with `ConcurrentHashMap` see:
https://guava.dev/releases/20.0/api/docs/com/google/common/util/concurrent/Striped.html
=> Switch to a striped lock for better concurrency.

examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlReplace.java
=> Add kubectl replace.

examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDelete.java
=> Add kubectl delete.

extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPatch.java
=> Add support for Kubectl patch

client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/pom.xml, extended/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring/pom.xml, util/pom.xml
Closes #1120 
This has been pushed out to Sonatype and should be visible in 24hr.
=> Release 10.0.0

README.md
and along w/ couple of minor updates
=> Chore: Adding known-issue section to README

extended/src/main/java/io/kubernetes/client/extended/pager/Pager.java, extended/src/test/java/io/kubernetes/client/extended/pager/PagerTest.java, extended/src/test/resources/namespace-list-pager0.json
=> Fix pager iterator and add test.

util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java, util/src/test/java/io/kubernetes/client/WebsocketStreamHandlerTest.java
=> Buffer writes > 16 MiB into multiple web socket messages.

util/src/main/java/io/kubernetes/client/util/Config.java, util/src/main/java/io/kubernetes/client/util/Namespaces.java
=> Add a helper method to obtain the namespace of a pod.

util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java, util/src/test/java/io/kubernetes/client/util/generic/KubernetesApiResponseTest.java
=> Bugfix: Suppress runtime exception upon non-status error responses

util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
Fixes: #1329 
@brendandburns @yue9944882
=> fix reflector graceful shutdown by closing underlying watch

docs/kubectl-equivalence-in-java.md, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPatch.java
@brendandburns plz feel free to help me fix the awkward english 😋
=> Doc: Kubectl Equivalence in Java

e2e/src/test/groovy/io/kubernetes/client/e2e/informer/NamespaceInformerTest.groovy, e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlDrainTest.groovy, e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlNamespaceTest.groovy, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCordon.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDrain.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlDrainTest.java
=> Fixes kubectl-drain failures and adding e2e tests

extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPatch.java
=> Add some null checking.

pom.xml, util/pom.xml, util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java, util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
Fixes #1367 
and with a few refactors that removes sleeping code
=> Reflector relists with last synced resource version

extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventAggregator.java, extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventLogger.java, extended/src/main/java/io/kubernetes/client/extended/workqueue/DefaultDelayingQueue.java, extended/src/test/java/io/kubernetes/client/extended/controller/ControllerManagerTest.java, spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java, util/src/test/java/io/kubernetes/client/WebsocketStreamHandlerTest.java, util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java
This is just for performance improvement.
Take look at [here](https://help.semmle.com/wiki/display/JAVA/Inner+class+could+be+static#:~:text=Description%3A%20A%20non%2Dstatic%20nested,may%20cause%20a%20memory%20leak.).
=> [Code cleanup] making nested class static

.github/workflows/maven.yml
See https://github.com/DeLaGuardo/setup-graalvm/issues/7
=> Update maven.yml fix graalvm tests

extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCordon.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlGet.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPatch.java
Fixes: https://github.com/kubernetes-client/java/issues/1394
=> Fixes a few places where the api-discovery is missed

pom.xml
=> Add source jars to deployment

extended/src/main/java/io/kubernetes/client/extended/controller/builder/DefaultControllerBuilder.java
Fixes https://github.com/kubernetes-client/java/issues/1195
=> Allow controller builder to set ready timeout

util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
JDT seems to have a problem with this code (but javac does not).
Users of Eclipse and VSCode will benefit if they need to edit
or build this project.
Fixes #1196
=> Cast to Runnable to avoid compiler error

.gitignore, extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventUtils.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlAnnotate.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDelete.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlGet.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlReplace.java, kubernetes/pom.xml, util/pom.xml
=> Make sundr codegen optional so it only applies to the k8s API code

extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElectionConfig.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElectionRecord.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/ConfigMapLock.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/EndpointsLock.java, extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/LeaseLock.java
Fixes https://github.com/kubernetes-client/java/issues/1089
=> Allow specify an owner reference for leader election lock

extended/src/main/java/io/kubernetes/client/extended/event/legacy/LegacyEventBroadcaster.java
we found worker leakage in some environments, this pull prevents potential leakage
=> Prevents event recorder worker thread leakage

.github/workflows/maven.yml
https://github.com/actions/cache/blob/main/examples.md#java---maven
=> Caching local maven repositories for github action jobs to reduce flakiness

pom.xml, util/pom.xml, util/src/main/java/io/kubernetes/client/Copy.java
=> Add path normalization for archive files.

client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/pom.xml, extended/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring/pom.xml, util/pom.xml
=> Release 10.0.1

spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/DeleteWatchEventFilter.java, spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/UpdateWatchEventFilter.java
Fixes: https://github.com/kubernetes-client/java/issues/1398
=> Swap javadoc for filter annotations

README.md
=> Add documentation for the FAQ

util/src/main/java/io/kubernetes/client/util/ModelMapper.java
Fixes: https://github.com/kubernetes-client/java/issues/1506
=> Chore: Removes stdout loggings

util/src/main/java/io/kubernetes/client/PortForward.java, util/src/main/java/io/kubernetes/client/util/ModelMapper.java, util/src/test/java/io/kubernetes/client/PortForwardTest.java
Included changes:
* Added handling and test for handling of communication failure during port forwarding;
* Added handling of possible NPE in ModelMapper during handling of non JAR paths;
=> Fixes to handle better error cases

extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventLogger.java
Fixes: https://github.com/kubernetes-client/java/issues/1536
cc @chris-chambers @brendandburns
=> Fixes event patching - unquote event count

e2e/src/test/groovy/io/kubernetes/client/e2e/basic/CoreV1ApiTest.groovy, e2e/src/test/groovy/io/kubernetes/client/e2e/csr/CSRTest.groovy, e2e/src/test/groovy/io/kubernetes/client/e2e/dynamic/DynamicApiTest.groovy, e2e/src/test/groovy/io/kubernetes/client/e2e/informer/NamespaceInformerTest.groovy, e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlDrainTest.groovy, e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlNamespaceTest.groovy, e2e/src/test/groovy/io/kubernetes/client/e2e/util/ModelMapperTest.groovy, pom.xml
spotless maven plugin began to support groovy formatting since Sep 2020, this pull adds groovy configuration
=> Spotless: groovy formatting

CHANGELOG.md
cc @brendandburns 
ref #1586 
/hold
after the new release is pushed
=> Release: Adding 12.0.0 release note

client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-10/pom.xml, examples/examples-release-11/pom.xml, examples/examples-release-12/pom.xml, examples/pom.xml, extended/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring/pom.xml, util/pom.xml
cc @yue9944882 
This has been pushed out to Sonatype and in 24hrs Maven Central
=> Release 12.0.0

util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
Fixes: https://github.com/kubernetes-client/java/issues/1606
=> Chore: Reducing rewatch logging verbosity upon normal re-connection

examples/examples-release-11/README.md, examples/examples-release-12/README.md, examples/examples-release-12/pom.xml, examples/examples-release-13/README.md
=> Improve docs for running examples.

pom.xml
There are quite a few fixes esp those related to HTTP/2 in okhttpclient.
=> Updating okhttpclient to 4.9.1

util/src/main/java/io/kubernetes/client/util/Yaml.java, util/src/test/java/io/kubernetes/client/util/TestPoJ.java, util/src/test/java/io/kubernetes/client/util/YamlTest.java, util/src/test/resources/pod-tag.yaml
=> Update the CustomConstructor class for SnakeYAML.

util/src/main/java/io/kubernetes/client/util/Yaml.java, util/src/test/java/io/kubernetes/client/util/TestPoJ.java, util/src/test/java/io/kubernetes/client/util/YamlTest.java, util/src/test/resources/pod-tag.yaml
cherry-picking https://github.com/kubernetes-client/java/pull/1676 to release-11
=> Cherry-pick 11: Update the CustomConstructor class for SnakeYAML

util/src/main/java/io/kubernetes/client/util/Yaml.java, util/src/test/java/io/kubernetes/client/util/TestPoJ.java, util/src/test/java/io/kubernetes/client/util/YamlTest.java, util/src/test/resources/pod-tag.yaml
cherry-picking https://github.com/kubernetes-client/java/pull/1676 to release-12
=> Cherry-pick 12: Update the CustomConstructor class for SnakeYAML

util/src/main/java/io/kubernetes/client/informer/ResyncRunnable.java, util/src/test/java/io/kubernetes/client/informer/ResyncRunnableTest.java
Fixes: https://github.com/kubernetes-client/java/issues/1721
@ydmao
=> Fixes duplicated SharedProcessor#shouldResync calls

.github/workflows/maven.yml, extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventAggregator.java, pom.xml, util/src/main/java/io/kubernetes/client/util/labels/LabelSelector.java, util/src/test/java/io/kubernetes/client/util/labels/LabelSelectorTest.java
@yue9944882 please check my changes.
This required some tweaking of imports but I think that maybe they were accidental?
=> Update to the latest sundr generator.

util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
=> Fix a test that was broken on some systems.

fluent-gen/pom.xml, fluent/pom.xml, pom.xml
also, this pull adds a new profile named `fluent-gen` to include the fluent-gen module so that we can opt-in to code-gen via `mvn -Pfluent-gen clean compile`
=> Chore: Trimming pom files for fluent modules

util/src/test/java/io/kubernetes/client/informer/cache/ControllerTest.java
Fixes: https://github.com/kubernetes-client/java/issues/1780
=> Flake: Reduce controller-test flakiness via awaitility

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-10/pom.xml, examples/examples-release-11/pom.xml, examples/examples-release-12/pom.xml, examples/examples-release-13/pom.xml, examples/pom.xml, extended/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring/pom.xml, util/pom.xml
=> Release 13.0.0

util/src/test/java/io/kubernetes/client/informer/cache/ProcessorListenerTest.java
sorry Forgot to add this class in last commit/pull request
https://github.com/kubernetes-client/java/issues/1223
=> remove Thread.sleep in ProcessorListenerTest.java

util/src/main/java/io/kubernetes/client/util/ModelMapper.java
this is a temporary remediation for https://github.com/kubernetes-client/java/issues/1659
=> Chore: Warn if no kubernetes api models were loaded

CHANGELOG.md
clarifying the changes since 12.0.0 -> 13.0.0. it's a bit lagged tho.
cc @brendandburns
=> Release note for 13.0.0

util/src/main/java/io/kubernetes/client/util/Yaml.java
ref https://github.com/kubernetes-client/gen/issues/196
=> Adding a constructor which accepts custom dumper/loader options

util/src/main/java/io/kubernetes/client/informer/cache/DeltaFIFO.java
There is no need to allocate a new list when removing the duplicate delta, it's more efficient to modify the list directly.
see https://github.com/kubernetes/kubernetes/commit/238fce9357634502badbcc3704b0655cf8c378c3
Besides, I removed some unnecessary casting.
=> Optimize DeltaFIFO.combineDeltas

util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java, util/src/main/java/io/kubernetes/client/informer/exception/WatchExpiredException.java, util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
Fixes: https://github.com/kubernetes-client/java/issues/1829
=> Bugfix: Stale watch event should be handled properly

util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
the `catch(WatchExpiredException)` block isnt actually working, this pull moves it to front and adds proper info-level loggings
cc @brendandburns @haoming-db
=> Chore: Sort list-watcher exception catch flow

util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Fixes: https://github.com/kubernetes-client/java/issues/1847
=> Bugfix: Passing list-options in generic api based informers

util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
picking https://github.com/kubernetes-client/java/pull/1852 to release-13
cc @brendandburns @pgressa 
will be getting this in release-13, then publish in the patch release
=> Cherry-pick(release-13): Passing list-options in generic api based informers

util/src/test/java/io/kubernetes/client/CopyTest.java, util/src/test/java/io/kubernetes/client/PortForwardTest.java
=> Kill some hard-coded sleep in tests

util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java, util/src/main/java/io/kubernetes/client/informer/exception/WatchExpiredException.java, util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
picks #1851 to 13 branch for next patch release
=> Cherrypick-13: Bugfix: stale watch event should be handled properly

util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
picks #1853 to 13 branch for next patch release
=> Cherrypick-13: Passing list-options in generic api based informers

client-java-contrib/Dockerfile, client-java-contrib/admissionreview/generate.sh, client-java-contrib/cert-manager/update.sh, client-java-contrib/prometheus-operator/update.sh, client-java-contrib/publish-gen-image.sh, docs/generate-model-from-third-party-resources.md
Fixes: https://github.com/kubernetes-client/java/issues/1915
=> CRD-Gen: Pin gen commit and bump 1.0.6

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-10/pom.xml, examples/examples-release-11/pom.xml, examples/examples-release-12/pom.xml, examples/examples-release-13/pom.xml, examples/pom.xml, extended/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring/pom.xml, util/pom.xml
=> Release 13.0.1

client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-10/pom.xml, examples/examples-release-11/pom.xml, examples/examples-release-12/pom.xml, examples/pom.xml, extended/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring/pom.xml, util/pom.xml
=> Release 12.0.2

client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/pom.xml, extended/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring/pom.xml, util/pom.xml
=> Release 11.0.3

.github/ISSUE_TEMPLATE/bug_report.md
Fix formatting so that all sections are rendered correctly in bold when creating an issue
=> Fix formatting

util/src/main/java/io/kubernetes/client/util/ClientBuilder.java, util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
Added null check with IllegalArgException and added a test case to ClientBuilderTest.
=> #1802 Check if server is available from kubeconfig.

.github/workflows/maven.yml
cc @yue9944882 
Related to #1980
=> Reduce the java matrix to just LTS versions.

util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java, util/src/main/java/io/kubernetes/client/informer/cache/Controller.java, util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java, util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java, util/src/main/java/io/kubernetes/client/util/ClientBuilder.java, util/src/test/java/io/kubernetes/client/informer/cache/ControllerTest.java, util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java, util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerTest.java, util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerWireMockTest.java, util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
Prepared the commits of #1802 (pr #1983) and #1629 (pr #1992) to be picked for release-14.
=> Cherry pick for #1802 and #1629 to release 14

spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java
https://github.com/kubernetes-client/java/pull/1963
=> Cherry Pick #1963 To Master

.github/workflows/snapshot.yml
s/MAVEN_GPG_PASSPHRASE/GPG_PASSPHRASE/
=> Release: Fixes snapshot job env var name

.github/workflows/snapshot.yml
> Signed-off-by: yue9944882 <291271447@qq.com>
=> Fixes snapshot job pt3

client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/pom.xml, extended/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring/pom.xml, util/pom.xml
@brendandburns i was testing automating the release via github action on release-10. as a result the `10.0.2` release is successfully pushed to nexus central. but the experiment was on my fork so i'm syncing the release commits to the upstream repo.
=> Sync automated release 10.0.2

.github/workflows/release.yml, RELEASES.md
> Signed-off-by: yue9944882 <291271447@qq.com>
=> Cherry-pick(release-11): Adding a release job receiving manual input

spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java
Would like #1963 in the 13.0 branch as well
=> Cherry Pick #1963 To 13.0

OWNERS
This PR solves Issue [https://github.com/kubernetes/community/issues/6334](https://github.com/kubernetes/community/issues/6334)
=> Fix OWNERS file : reviewer to reviewers

kubernetes/src/main/java/io/kubernetes/client/openapi/JSON.java
=> Fix the default datetime formatter of OffsetDateTime dropping time zone info

extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlApply.java, extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlApplyTest.java, util/src/main/java/io/kubernetes/client/util/ModelMapper.java
Addresses #2318 (I think)
@yue9944882 this is a sketch, let me know if you think it looks ok and I will add tests.
=> Add support for dynamic objects to kubectl apply.

util/src/main/java/io/kubernetes/client/util/authenticators/AzureActiveDirectoryAuthenticator.java
=> Add null handling for a missing expiresOn field.

README.md
Attach: #2380
link added to the build batch
previously it re-direct to the image 
now it re-direct to the actual build link
=> docs(build): link added to build badge #2380

extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultRateLimitQueueTest.java
=> Improve the test to better debug flakiness (and maybe fix it)

extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlExec.java, extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPortForward.java, util/src/main/java/io/kubernetes/client/Exec.java, util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java, util/src/test/java/io/kubernetes/client/ExecTest.java
Cherry-pick of the following bug fixes: 
* https://github.com/kubernetes-client/java/pull/2366
* https://github.com/kubernetes-client/java/pull/2387
* https://github.com/kubernetes-client/java/pull/2388
=> Cherry pick 16: some bug fixes

examples/examples-release-14/src/main/java/io/kubernetes/client/examples/ExpandedExample.java
Updated comment from <code>List all of the **namaspaces** and pods</code> to <code>List all of the **namespaces** and pods</code>
=> Updated expanded example comment

util/src/test/java/io/kubernetes/client/util/SSLUtilsTest.java
This pull request refactors `SSLUtilsTest` to use a shared test method for loading and reloading private keys. Additional changes include a new test for the ECDSA PKCS8 private key, and assertions for the Private Key Algorithm of the parsed key.
See issue #2440 and pull request #2441 for related background on `SSLUtils` private key loading.
=> Refactor SSLUtilsTest with shared method and algorithm assertions

.github/workflows/release.yml, .github/workflows/snapshot.yml
Cherry picks #2487 #2484  into the release-17 branch.
cc @yue9944882
=> Cherry pick some github actions fixes into the release-17 branch.

pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
a follow-up of #2457, cleaning up some pom configurations, it doesnt involve effective change to the project
=> Chore: Merge jacoco maven plugin declaration to parent pom

docs/generate-model-from-third-party-resources.md
Going through the CRD docs I noticed that the link was invalid
=> Fix path for CRD GHA in docs

pom.xml, util/src/main/java/io/kubernetes/client/util/FilePersister.java, util/src/main/java/io/kubernetes/client/util/generic/dynamic/Dynamics.java
=> [Cherry-pick] Add a rule to block empty YAML constructors.

util/src/main/java/io/kubernetes/client/informer/cache/Cache.java
Fixes: https://github.com/kubernetes-client/java/issues/2548
=> Bugfix: Fixes indexKeys NPE

util/src/main/java/io/kubernetes/client/util/Threads.java
**added ability to inject threads**
solves #2509
=> added ability to inject threads

util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
add exceptionHandler for SharedInformerFactory.sharedIndexInformerFor
#2603
=> add exceptionHandler for SharedInformerFactory.sharedIndexInformerFor

extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
I'm going to update LeaderElector not to emit error logs while graceful shutdown.
I got the error log below when I restart an application using LeaderElector even if I gracefully shutdown it.
https://github.com/kubernetes-client/java/blob/39a29b92345698a91c8717776dbcc5ad4e7acf86/extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java#L209
The reason is that executors were closed by `shutdownNow` method.
So I updated codes to use `shutdown` method instead and await termination for a while.
=> tweak graceful shutdown of LeaderElector

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-13/pom.xml, examples/examples-release-14/pom.xml, examples/examples-release-15/pom.xml, examples/pom.xml, extended/pom.xml, fluent-gen/pom.xml, fluent/pom.xml, kubernetes/pom.xml, kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
this is required upon cutting every release from the main branch
=> Bump latest snapshot to 19.0.0-SNAPSHOT

client-java-contrib/generate.sh
Now, it's "kind" by default name, and it's easy to conflict. And then just got the error:
```
ERROR: failed to create cluster: node(s) already exist for a cluster with the name "kind"
```
So this PR have two changes:
* Change kind cluster default name to crd-model-gen
* Support set name of kind
=> Support name of kind and crd-model-gen by default name

kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java, kubernetes/src/test/java/io/kubernetes/client/custom/QuantityFormatterTest.java
=> No need to compare format when compare Quantity

kubernetes/pom.xml, pom.xml
See this failure:
https://github.com/kubernetes-client/java/actions/runs/6354556302/job/17261167163
=> Add jakarta.annotation dependency for future code generation.

pom.xml
See #2826 and #2753 
cc @yue9944882
=> Cherry pick #2826 Update pom.xml into release 19 branch.

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-16/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/pom.xml, extended/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
So that we can publish 19.0.0 again from release-19 branch @brendandburns
=> Release-19: Reset release 19 pom version to 19.0.0-SNAPSHOT

examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml
Same as #2832 but for the release-19 branch.
=> Update pom for release-19 examples [cherrypick to release-19 branch]

pom.xml
https://github.com/kubernetes-client/java/issues/2973
Just because owner of https://github.com/kubernetes-client/java/pull/2988 is not actively working on it.
=> Upgrade okhttp to 4.12.0

kubernetes/src/main/java/io/kubernetes/client/custom/MapUtils.java, kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1Secret.java, kubernetes/src/test/java/io/kubernetes/client/custom/MapUtilsTest.java, kubernetes/src/test/java/io/kubernetes/client/openapi/V1SecretTest.java, scripts/patches/secret.diff
Fixes: https://github.com/kubernetes-client/java/issues/431
=> Fixes secret deep-compare issue and track the change by patches

client-java-contrib/generate.sh
=> Add additional command line argument for client generation script

.github/workflows/release.yml
The validation step failed here: https://github.com/kubernetes-client/java/actions/runs/7807886430
=> Release: Adjust release workflow validate logic for legacy-branch

e2e/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/examples-release-20/pom.xml, examples/examples-release-latest/pom.xml
also removed redundant versions in the skip config for examples
=> Skip deployment of E2E test module to maven repository

pom.xml
See https://github.com/kubernetes-client/java/issues/3156
=> Upgrade to apache commons compress 1.26.1

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-16/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/pom.xml, extended/pom.xml, fluent-gen/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
=> Fix typo in pom.xml

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-16/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/pom.xml, extended/pom.xml, fluent-gen/pom.xml, fluent/pom.xml, kubernetes/pom.xml, kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
Preparing for 1.30 (21.0.0) release, bumping the root pom version.
=> branch(Java8): Bump 20.0.0-legacy-SNAPSHOT to 21.0.0-legacy-SNAPSHOT

examples/examples-release-17/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java, examples/examples-release-18/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java, examples/examples-release-19/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java, examples/examples-release-20/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java, examples/examples-release-latest/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java
closes: #3506 
Updated the comments to make it consistent in example code.
=> Fix for comment in example code snippet is inconsistent #3506

.github/workflows/codeql-analysis.yml
=> Update codeql action to remove autobuild

extended/pom.xml, fluent-gen/pom.xml, pom.xml, spring/pom.xml, util/pom.xml
Fix for https://github.com/kubernetes-client/java/issues/3596
=> optional 3rd party ignored (issue #3596)

pom.xml
=> upgrade protobuf

.github/workflows/generate.yml
Hopefully this fixes https://github.com/kubernetes/org/issues/5126
=> Add permissions to create pull requests to gh action

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-latest/pom.xml, examples/pom.xml, extended/pom.xml, fluent-gen/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
Needed for the release github action to work correctly
=> Update poms for 22.0.0 release

.github/workflows/release.yml
=> Clarifying legacy release workflow instructions

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/examples-release-20/pom.xml, examples/examples-release-latest/pom.xml, examples/pom.xml, extended/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
Copying the generated PR from fork to main repo: https://github.com/yue9944882/java/pull/100
I will follow-up tag the v22.0.0-legacy manually
=> Automated Release: 22.0.0-legacy 

scripts/patches/json.diff, scripts/patches/list-meta.diff, scripts/patches/secret.diff, scripts/patches/status.diff
This PR fixes the workflow failure that caused by code patch step: https://github.com/kubernetes-client/java/actions/runs/13120777699
=> Refreshes the patches files

.github/workflows/generate.yml, .github/workflows/release.yml, scripts/patches/json.diff, scripts/patches/list-meta.diff, scripts/patches/secret.diff, scripts/patches/status.diff
This PR syncs up some repo infra resources between master-java8 and master branches.
=> Chore: Sync up repo infra assets from master branch

kubernetes/pom.xml, kubernetes/src/main/java/io/kubernetes/client/custom/MapUtils.java, kubernetes/src/main/java/io/kubernetes/client/gson/V1MetadataExclusionStrategy.java, pom.xml
This PR syncs some source files that's missing in master-java8 branch but required for model generation workflow.
=> Branch(master-java8): Sync missing source files from master branch

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-16/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/pom.xml, extended/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
Ref: https://github.com/yue9944882/java/pull/110
=> Automated release 22.0.1 legacy

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/examples-release-20/pom.xml, examples/examples-release-latest/pom.xml, examples/pom.xml, extended/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
Ref: https://github.com/yue9944882/java/pull/109
=> Automated release 22.0.1

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/examples-release-20/pom.xml, examples/examples-release-latest/pom.xml, examples/pom.xml, extended/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml, util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesListApiTest.java
Cut 23.0.0 release.
Ref: #3924
=> Branch(release-23): Automated release 23.0.0

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-16/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/pom.xml, extended/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
Cut release-legacy-23 release
Ref: #3924
=> Branch(release-legacy-23): Automated release 23.0.0 legacy

extended/src/test/java/io/kubernetes/client/extended/controller/DefaultControllerTest.java
=> Deflake a test

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/examples-release-20/pom.xml, examples/examples-release-latest/pom.xml, examples/pom.xml, extended/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
GH release job: https://github.com/yue9944882/java/actions/runs/15217107346/job/42805029761
Original PR: https://github.com/yue9944882/java/pull/123
=> Automated release 24.0.0

client-java-contrib/admissionreview/pom.xml, client-java-contrib/cert-manager/pom.xml, client-java-contrib/prometheus-operator/pom.xml, e2e/pom.xml, examples/examples-release-16/pom.xml, examples/examples-release-17/pom.xml, examples/examples-release-18/pom.xml, examples/examples-release-19/pom.xml, examples/pom.xml, extended/pom.xml, fluent/pom.xml, kubernetes/pom.xml, pom.xml, proto/pom.xml, spring-aot/pom.xml, spring/pom.xml, util/pom.xml
GH release job: https://github.com/yue9944882/java/actions/runs/15218963083/job/42810743403
Original PR: https://github.com/yue9944882/java/pull/124
=> Automated release 24.0.0 legacy
